<a href="https://colab.research.google.com/github/iking919/Detecting_Financial_Fraud_via_GNNs/blob/tuning-GNN/notebooks/04_GNN_models.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# GNN Modeling

### Data Extraction
First, we mount Google Drive to access our dataset and extract the processed graph data from a ZIP archive so we can use it locally in the Colab instance.

In [37]:
from google.colab import drive
import zipfile

# mount drive
drive.mount('/content/drive')

drive_path = '/content/drive/MyDrive/GNN_fraud_Project/processed_data.zip'
extract_path = '/content'

# unzip the processed data locally to speed things up
with zipfile.ZipFile(drive_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

### Data Inspection
We load and inspect the first few rows of the extracted CSV files to ensure all data was extracted correctly.

In [38]:
import os
import pandas as pd

extract_path = '/content/data/processed'
csv_files = [f for f in os.listdir(extract_path) if f.endswith('.csv')]

for file in csv_files:
    file_path = os.path.join(extract_path, file)

    # Read just the first few rows to quickly inspect columns and types
    df = pd.read_csv(file_path, nrows=5)
    print(f"\n{'='*40}\nDataset: {file}\n{'='*40}")
    print(f"Number of features: {len(df.columns)}")
    print("Features:", list(df.columns))
    display(df.head(2))

========================================
Dataset: elliptic_nodes.csv
========================================
Number of features: 168
Features: ['timestep', 'feature_1', 'feature_2', 'feature_3', 'feature_4', 'feature_5', 'feature_6', 'feature_7', 'feature_8', 'feature_9', 'feature_10', 'feature_11', 'feature_12', 'feature_13', 'feature_14', 'feature_15', 'feature_16', 'feature_17', 'feature_18', 'feature_19', 'feature_20', 'feature_21', 'feature_22', 'feature_23', 'feature_24', 'feature_25', 'feature_26', 'feature_27', 'feature_28', 'feature_29', 'feature_30', 'feature_31', 'feature_32', 'feature_33', 'feature_34', 'feature_35', 'feature_36', 'feature_37', 'feature_38', 'feature_39', 'feature_40', 'feature_41', 'feature_42', 'feature_43', 'feature_44', 'feature_45', 'feature_46', 'feature_47', 'feature_48', 'feature_49', 'feature_50', 'feature_51', 'feature_52', 'feature_53', 'feature_54', 'feature_55', 'feature_56', 'feature_57', 'feature_58', 'feature_59', 'feature_60', 'feature_61', 'feature_62', 'feature_63', 'feature_64', 'feature_65', 'feature_66', 'feature_67', 'feature_68', 'feature_69', 'feature_70', 'feature_71', 'feature_72', 'feature_73', 'feature_74', 'feature_75', 'feature_76', 'feature_77', 'feature_78', 'feature_79', 'feature_80', 'feature_81', 'feature_82', 'feature_83', 'feature_84', 'feature_85', 'feature_86', 'feature_87', 'feature_88', 'feature_89', 'feature_90', 'feature_91', 'feature_92', 'feature_93', 'feature_94', 'feature_95', 'feature_96', 'feature_97', 'feature_98', 'feature_99', 'feature_100', 'feature_101', 'feature_102', 'feature_103', 'feature_104', 'feature_105', 'feature_106', 'feature_107', 'feature_108', 'feature_109', 'feature_110', 'feature_111', 'feature_112', 'feature_113', 'feature_114', 'feature_115', 'feature_116', 'feature_117', 'feature_118', 'feature_119', 'feature_120', 'feature_121', 'feature_122', 'feature_123', 'feature_124', 'feature_125', 'feature_126', 'feature_127', 'feature_128', 'feature_129', 'feature_130', 'feature_131', 'feature_132', 'feature_133', 'feature_134', 'feature_135', 'feature_136', 'feature_137', 'feature_138', 'feature_139', 'feature_140', 'feature_141', 'feature_142', 'feature_143', 'feature_144', 'feature_145', 'feature_146', 'feature_147', 'feature_148', 'feature_149', 'feature_150', 'feature_151', 'feature_152', 'feature_153', 'feature_154', 'feature_155', 'feature_156', 'feature_157', 'feature_158', 'feature_159', 'feature_160', 'feature_161', 'feature_162', 'feature_163', 'feature_164', 'feature_165', 'tx_id', 'label']

,timestep,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,...,feature_158,feature_159,feature_160,feature_161,feature_162,feature_163,feature_164,feature_165,tx_id,label
0,-1.556878,0.307025,1.168821,-0.748109,7.643807,-0.053406,6.039024,21.528480,-0.146334,-0.084347,...,0.155526,0.155844,2.115930,0.016322,-0.117599,0.593442,-0.08332,-0.082052,NaN,2
1,-1.556878,0.067780,0.271911,-0.226081,2.628539,-0.053406,2.820415,1.501088,-0.146334,-0.127352,...,0.155526,0.155844,1.200416,-0.028141,-0.117599,0.270020,-0.08332,-0.082052,NaN,2

========================================
Dataset: elliptic_edges.csv
========================================
Number of features: 2
Features: ['source', 'target']

      source     target
0  230425980    5530458
1  232022460  232438397

========================================
Dataset: ieee_train_nodes.csv
========================================
Number of features: 434
Features: ['TransactionDT', 'TransactionAmt', 'ProductCD', 'card1', 'card2', 'card3', 'card4', 'card5', 'card6', 'addr1', 'addr2', 'dist1', 'dist2', 'P_emaildomain', 'R_emaildomain', 'C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7', 'C8', 'C9', 'C10', 'C11', 'C12', 'C13', 'C14', 'D1', 'D2', 'D3', 'D4', 'D5', 'D6', 'D7', 'D8', 'D9', 'D10', 'D11', 'D12', 'D13', 'D14', 'D15', 'M1', 'M2', 'M3', 'M4', 'M5', 'M6', 'M7', 'M8', 'M9', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10', 'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20', 'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'V29', 'V30', 'V31', 'V32', 'V33', 'V34', 'V35', 'V36', 'V37', 'V38', 'V39', 'V40', 'V41', 'V42', 'V43', 'V44', 'V45', 'V46', 'V47', 'V48', 'V49', 'V50', 'V51', 'V52', 'V53', 'V54', 'V55', 'V56', 'V57', 'V58', 'V59', 'V60', 'V61', 'V62', 'V63', 'V64', 'V65', 'V66', 'V67', 'V68', 'V69', 'V70', 'V71', 'V72', 'V73', 'V74', 'V75', 'V76', 'V77', 'V78', 'V79', 'V80', 'V81', 'V82', 'V83', 'V84', 'V85', 'V86', 'V87', 'V88', 'V89', 'V90', 'V91', 'V92', 'V93', 'V94', 'V95', 'V96', 'V97', 'V98', 'V99', 'V100', 'V101', 'V102', 'V103', 'V104', 'V105', 'V106', 'V107', 'V108', 'V109', 'V110', 'V111', 'V112', 'V113', 'V114', 'V115', 'V116', 'V117', 'V118', 'V119', 'V120', 'V121', 'V122', 'V123', 'V124', 'V125', 'V126', 'V127', 'V128', 'V129', 'V130', 'V131', 'V132', 'V133', 'V134', 'V135', 'V136', 'V137', 'V138', 'V139', 'V140', 'V141', 'V142', 'V143', 'V144', 'V145', 'V146', 'V147', 'V148', 'V149', 'V150', 'V151', 'V152', 'V153', 'V154', 'V155', 'V156', 'V157', 'V158', 'V159', 'V160', 'V161', 'V162', 'V163', 'V164', 'V165', 'V166', 'V167', 'V168', 'V169', 'V170', 'V171', 'V172', 'V173', 'V174', 'V175', 'V176', 'V177', 'V178', 'V179', 'V180', 'V181', 'V182', 'V183', 'V184', 'V185', 'V186', 'V187', 'V188', 'V189', 'V190', 'V191', 'V192', 'V193', 'V194', 'V195', 'V196', 'V197', 'V198', 'V199', 'V200', 'V201', 'V202', 'V203', 'V204', 'V205', 'V206', 'V207', 'V208', 'V209', 'V210', 'V211', 'V212', 'V213', 'V214', 'V215', 'V216', 'V217', 'V218', 'V219', 'V220', 'V221', 'V222', 'V223', 'V224', 'V225', 'V226', 'V227', 'V228', 'V229', 'V230', 'V231', 'V232', 'V233', 'V234', 'V235', 'V236', 'V237', 'V238', 'V239', 'V240', 'V241', 'V242', 'V243', 'V244', 'V245', 'V246', 'V247', 'V248', 'V249', 'V250', 'V251', 'V252', 'V253', 'V254', 'V255', 'V256', 'V257', 'V258', 'V259', 'V260', 'V261', 'V262', 'V263', 'V264', 'V265', 'V266', 'V267', 'V268', 'V269', 'V270', 'V271', 'V272', 'V273', 'V274', 'V275', 'V276', 'V277', 'V278', 'V279', 'V280', 'V281', 'V282', 'V283', 'V284', 'V285', 'V286', 'V287', 'V288', 'V289', 'V290', 'V291', 'V292', 'V293', 'V294', 'V295', 'V296', 'V297', 'V298', 'V299', 'V300', 'V301', 'V302', 'V303', 'V304', 'V305', 'V306', 'V307', 'V308', 'V309', 'V310', 'V311', 'V312', 'V313', 'V314', 'V315', 'V316', 'V317', 'V318', 'V319', 'V320', 'V321', 'V322', 'V323', 'V324', 'V325', 'V326', 'V327', 'V328', 'V329', 'V330', 'V331', 'V332', 'V333', 'V334', 'V335', 'V336', 'V337', 'V338', 'V339', 'id_01', 'id_02', 'id_03', 'id_04', 'id_05', 'id_06', 'id_07', 'id_08', 'id_09', 'id_10', 'id_11', 'id_12', 'id_13', 'id_14', 'id_15', 'id_16', 'id_17', 'id_18', 'id_19', 'id_20', 'id_21', 'id_22', 'id_23', 'id_24', 'id_25', 'id_26', 'id_27', 'id_28', 'id_29', 'id_30', 'id_31', 'id_32', 'id_33', 'id_34', 'id_35', 'id_36', 'id_37', 'id_38', 'DeviceType', 'DeviceInfo', 'tx_id', 'label']

,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,card6,addr1,...,id_33,id_34,id_35,id_36,id_37,id_38,DeviceType,DeviceInfo,tx_id,label
0,-1.577987,-0.278167,0.54725,0.821695,-0.009783,-0.281425,-2.187837,-1.396380,-1.675109,0.243321,...,0.349681,0.36423,0.521097,0.555553,0.522078,0.524266,0.528289,0.319736,0,0
1,-1.577986,-0.443327,0.54725,-1.457558,0.264810,-0.281425,-1.222461,-2.368254,-1.675109,0.347543,...,0.349681,0.36423,0.521097,0.555553,0.522078,0.524266,0.528289,0.319736,1,0

========================================
Dataset: ieee_test_nodes.csv
========================================
Number of features: 433
Features: ['TransactionDT', 'TransactionAmt', 'ProductCD', 'card1', 'card2', 'card3', 'card4', 'card5', 'card6', 'addr1', 'addr2', 'dist1', 'dist2', 'P_emaildomain', 'R_emaildomain', 'C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7', 'C8', 'C9', 'C10', 'C11', 'C12', 'C13', 'C14', 'D1', 'D2', 'D3', 'D4', 'D5', 'D6', 'D7', 'D8', 'D9', 'D10', 'D11', 'D12', 'D13', 'D14', 'D15', 'M1', 'M2', 'M3', 'M4', 'M5', 'M6', 'M7', 'M8', 'M9', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10', 'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20', 'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'V29', 'V30', 'V31', 'V32', 'V33', 'V34', 'V35', 'V36', 'V37', 'V38', 'V39', 'V40', 'V41', 'V42', 'V43', 'V44', 'V45', 'V46', 'V47', 'V48', 'V49', 'V50', 'V51', 'V52', 'V53', 'V54', 'V55', 'V56', 'V57', 'V58', 'V59', 'V60', 'V61', 'V62', 'V63', 'V64', 'V65', 'V66', 'V67', 'V68', 'V69', 'V70', 'V71', 'V72', 'V73', 'V74', 'V75', 'V76', 'V77', 'V78', 'V79', 'V80', 'V81', 'V82', 'V83', 'V84', 'V85', 'V86', 'V87', 'V88', 'V89', 'V90', 'V91', 'V92', 'V93', 'V94', 'V95', 'V96', 'V97', 'V98', 'V99', 'V100', 'V101', 'V102', 'V103', 'V104', 'V105', 'V106', 'V107', 'V108', 'V109', 'V110', 'V111', 'V112', 'V113', 'V114', 'V115', 'V116', 'V117', 'V118', 'V119', 'V120', 'V121', 'V122', 'V123', 'V124', 'V125', 'V126', 'V127', 'V128', 'V129', 'V130', 'V131', 'V132', 'V133', 'V134', 'V135', 'V136', 'V137', 'V138', 'V139', 'V140', 'V141', 'V142', 'V143', 'V144', 'V145', 'V146', 'V147', 'V148', 'V149', 'V150', 'V151', 'V152', 'V153', 'V154', 'V155', 'V156', 'V157', 'V158', 'V159', 'V160', 'V161', 'V162', 'V163', 'V164', 'V165', 'V166', 'V167', 'V168', 'V169', 'V170', 'V171', 'V172', 'V173', 'V174', 'V175', 'V176', 'V177', 'V178', 'V179', 'V180', 'V181', 'V182', 'V183', 'V184', 'V185', 'V186', 'V187', 'V188', 'V189', 'V190', 'V191', 'V192', 'V193', 'V194', 'V195', 'V196', 'V197', 'V198', 'V199', 'V200', 'V201', 'V202', 'V203', 'V204', 'V205', 'V206', 'V207', 'V208', 'V209', 'V210', 'V211', 'V212', 'V213', 'V214', 'V215', 'V216', 'V217', 'V218', 'V219', 'V220', 'V221', 'V222', 'V223', 'V224', 'V225', 'V226', 'V227', 'V228', 'V229', 'V230', 'V231', 'V232', 'V233', 'V234', 'V235', 'V236', 'V237', 'V238', 'V239', 'V240', 'V241', 'V242', 'V243', 'V244', 'V245', 'V246', 'V247', 'V248', 'V249', 'V250', 'V251', 'V252', 'V253', 'V254', 'V255', 'V256', 'V257', 'V258', 'V259', 'V260', 'V261', 'V262', 'V263', 'V264', 'V265', 'V266', 'V267', 'V268', 'V269', 'V270', 'V271', 'V272', 'V273', 'V274', 'V275', 'V276', 'V277', 'V278', 'V279', 'V280', 'V281', 'V282', 'V283', 'V284', 'V285', 'V286', 'V287', 'V288', 'V289', 'V290', 'V291', 'V292', 'V293', 'V294', 'V295', 'V296', 'V297', 'V298', 'V299', 'V300', 'V301', 'V302', 'V303', 'V304', 'V305', 'V306', 'V307', 'V308', 'V309', 'V310', 'V311', 'V312', 'V313', 'V314', 'V315', 'V316', 'V317', 'V318', 'V319', 'V320', 'V321', 'V322', 'V323', 'V324', 'V325', 'V326', 'V327', 'V328', 'V329', 'V330', 'V331', 'V332', 'V333', 'V334', 'V335', 'V336', 'V337', 'V338', 'V339', 'id-01', 'id-02', 'id-03', 'id-04', 'id-05', 'id-06', 'id-07', 'id-08', 'id-09', 'id-10', 'id-11', 'id-12', 'id-13', 'id-14', 'id-15', 'id-16', 'id-17', 'id-18', 'id-19', 'id-20', 'id-21', 'id-22', 'id-23', 'id-24', 'id-25', 'id-26', 'id-27', 'id-28', 'id-29', 'id-30', 'id-31', 'id-32', 'id-33', 'id-34', 'id-35', 'id-36', 'id-37', 'id-38', 'DeviceType', 'DeviceInfo', 'tx_id']

,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,card6,addr1,...,id-32,id-33,id-34,id-35,id-36,id-37,id-38,DeviceType,DeviceInfo,tx_id
0,-1.792644,-0.418162,0.591741,0.092483,-1.606985,-0.283858,0.691996,0.632954,0.526399,-1.288870,...,-0.199723,0.37658,0.407556,0.565944,0.605893,0.564739,0.579979,0.569268,0.341874,0
1,-1.792635,-0.348790,0.591741,-1.163823,-1.606985,-0.283858,0.691996,0.632954,0.526399,0.065373,...,-0.199723,0.37658,0.407556,0.565944,0.605893,0.564739,0.579979,0.569268,0.341874,1

========================================
Dataset: paysim_nodes.csv
========================================
Number of features: 9
Features: ['log_amount', 'type_encoded', 'oldbalanceOrg', 'newbalanceOrig', 'oldbalanceDest', 'newbalanceDest', 'step', 'tx_id', 'label']

,log_amount,type_encoded,oldbalanceOrg,newbalanceOrig,oldbalanceDest,newbalanceDest,step,tx_id,label
0,-0.907462,0.952399,-0.229810,-0.237622,-0.323814,-0.333411,-1.703042,0,0
1,-1.824023,0.952399,-0.281359,-0.285812,-0.323814,-0.333411,-1.703042,1,0

========================================
Dataset: ieee_train_edges.csv
========================================
Number of features: 2
Features: ['source', 'target']

   source  target
0   36634  164336
1  164336  223739

========================================
Dataset: paysim_edges.csv
========================================
Number of features: 2
Features: ['source', 'target']

   source   target
0      95  2192036
1     834  1359401

========================================
Dataset: ieee_test_edges.csv
========================================
Number of features: 2
Features: ['source', 'target']

   source  target
0  420980  449477
1  381391  393300

### Environment Setup
We need to install the `torch_geometric` library, which provides the necessary modules for building and training our Graph Neural Networks.

In [39]:
!pip install torch_geometric

Requirement already satisfied: torch_geometric in /usr/local/lib/python3.12/dist-packages (2.7.0)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.12/dist-packages (from torch_geometric) (3.13.5)
Requirement already satisfied: fsspec in /usr/local/lib/python3.12/dist-packages (from torch_geometric) (2025.3.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch_geometric) (3.1.6)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from torch_geometric) (2.0.2)
Requirement already satisfied: psutil>=5.8.0 in /usr/local/lib/python3.12/dist-packages (from torch_geometric) (5.9.5)
Requirement already satisfied: pyparsing in /usr/local/lib/python3.12/dist-packages (from torch_geometric) (3.3.2)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from torch_geometric) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from torch_geometric) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from torch_geometric) (3.6.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch_geometric) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch_geometric) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch_geometric) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch_geometric) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch_geometric) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch_geometric) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch_geometric) (1.23.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch_geometric) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->torch_geometric) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->torch_geometric) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->torch_geometric) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->torch_geometric) (2026.2.25)
Requirement already satisfied: typing-extensions>=4.2 in /usr/local/lib/python3.12/dist-packages (from aiosignal>=1.4.0->aiohttp->torch_geometric) (4.15.0)

### Library Imports and Seed Initialization
Here we import necessary libraries such as PyTorch, PyTorch Geometric, Pandas, and Scikit-Learn. We also set universal random seeds across NumPy and PyTorch to ensure our experiments are reproducible.

In [40]:
import random
import pandas as pd
import numpy as np
import torch
import torch.nn.functional as F
from torch_geometric.data import Data
from torch_geometric.nn import SAGEConv
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.metrics import roc_auc_score, f1_score, confusion_matrix, classification_report
from sklearn.model_selection import train_test_split

# Set seed for reproducibility
seed = 42

random.seed(seed)
np.random.seed(seed)
torch.manual_seed(seed)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(seed)

## GraphSAGE (Graph Sample and Aggregate) Model

### GraphSAGE Definition and Utilities
Below, we define the `FraudGraphSAGE` model architecture. Additionally, we establish critical utility functions:
*   `load_graph_data`: Handles loading nodes/edges, preprocessing features (imputation, scaling), splitting the dataset, and dynamically calculating base positive weights to combat class imbalance.
*   `train_gnn` & `evaluate_gnn`: Standardized training and evaluation loops with early stopping.

In [41]:
from sklearn.metrics import average_precision_score

class FraudGraphSAGE(torch.nn.Module):
    def __init__(self, in_channels, hidden_channels, out_channels):
        super(FraudGraphSAGE, self).__init__()
        self.conv1 = SAGEConv(in_channels, hidden_channels)
        self.conv2 = SAGEConv(hidden_channels, out_channels)

    def forward(self, x, edge_index):
        x = self.conv1(x, edge_index)
        x = F.relu(x)
        # 50% dropout seems to work best
        x = F.dropout(x, p=0.5, training=self.training)
        x = self.conv2(x, edge_index)
        return x

def load_graph_data(nodes_filepath, edges_filepath, target_col):
    print(f"Loading graph data...")
    nodes_df = pd.read_csv(nodes_filepath)
    edges_df = pd.read_csv(edges_filepath)

    # clean up labeling
    label_mapping = {'1': 1, 1: 1, '2': 0, 2: 0, 'unknown': -1, '3': -1, 3: -1, '0': 0, 0: 0}
    nodes_df[target_col] = nodes_df[target_col].map(label_mapping)

    node_id_col = 'tx_id' if 'tx_id' in nodes_df.columns else ('TransactionID' if 'TransactionID' in nodes_df.columns else None)

    if node_id_col:
        # drop dupes just in case
        if nodes_df[node_id_col].duplicated().any():
            print(f"Warning: Duplicate node IDs found in '{node_id_col}'. Keeping first.")
            nodes_df = nodes_df.drop_duplicates(subset=[node_id_col], keep='first')

        original_node_ids = nodes_df[node_id_col].values
        node_id_to_idx = {id: i for i, id in enumerate(original_node_ids)}

        # remap edges to 0-indexed ints
        edges_df['source'] = edges_df['source'].map(node_id_to_idx)
        edges_df['target'] = edges_df['target'].map(node_id_to_idx)
        edges_df.dropna(subset=['source', 'target'], inplace=True)

        features_to_drop = [target_col, node_id_col]
        X = nodes_df.drop(columns=features_to_drop, errors='ignore').select_dtypes(include=[np.number]).values
    else:
        X = nodes_df.drop(columns=[target_col], errors='ignore').select_dtypes(include=[np.number]).values

    y = nodes_df[target_col].values

    # basic imputation and scaling
    imputer = SimpleImputer(strategy='mean')
    X_imputed = imputer.fit_transform(X)
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X_imputed)

    x_tensor = torch.tensor(X_scaled, dtype=torch.float)
    y_tensor = torch.tensor(y, dtype=torch.float)

    source_nodes = edges_df['source'].astype(int).values
    target_nodes = edges_df['target'].astype(int).values
    edge_index = torch.tensor(np.vstack((source_nodes, target_nodes)), dtype=torch.long)

    data = Data(x=x_tensor, edge_index=edge_index, y=y_tensor)

    # only split on nodes we actually have labels for
    known_indices = np.where((y == 0) | (y == 1))[0]

    if len(np.unique(y[known_indices])) < 2:
        train_indices, test_indices = train_test_split(known_indices, test_size=0.2, random_state=42)
    else:
        train_indices, test_indices = train_test_split(known_indices, test_size=0.2, stratify=y[known_indices], random_state=42)

    train_mask = torch.zeros(data.num_nodes, dtype=torch.bool)
    test_mask = torch.zeros(data.num_nodes, dtype=torch.bool)
    train_mask[train_indices] = True
    test_mask[test_indices] = True
    data.train_mask = train_mask
    data.test_mask = test_mask

    # initial weight calc (usually gets overridden in sweeps)
    num_pos = int((y_tensor[train_mask] == 1).sum().item())
    num_neg = int((y_tensor[train_mask] == 0).sum().item())
    raw_weight = num_neg / max(1, num_pos)
    capped_weight = min(10.0, raw_weight)
    pos_weight = torch.tensor([capped_weight], dtype=torch.float)

    return data, pos_weight

def train_gnn(model, data, pos_weight, device, epochs=300, lr=0.01, patience=30):
    model.to(device)
    data = data.to(device)
    pos_weight = pos_weight.to(device)

    criterion = torch.nn.BCEWithLogitsLoss(pos_weight=pos_weight)
    optimizer = torch.optim.Adam(model.parameters(), lr=lr, weight_decay=5e-4)

    best_loss = float('inf')
    patience_counter = 0

    for epoch in range(epochs):
        model.train()
        optimizer.zero_grad()
        out = model(data.x, data.edge_index).squeeze()
        loss = criterion(out[data.train_mask], data.y[data.train_mask])
        loss.backward()
        optimizer.step()

        # tracking for early stopping
        if loss.item() < best_loss:
            best_loss = loss.item()
            patience_counter = 0
        else:
            patience_counter += 1

        if (epoch + 1) % 50 == 0:
            print(f'Epoch {epoch+1:03d}/{epochs} | Loss: {loss:.4f}')

        if patience_counter >= patience:
            print(f'Early stopping at epoch {epoch+1} (Loss: {loss:.4f})')
            break

def evaluate_gnn(model, data, device):
    model.eval()
    data = data.to(device)
    with torch.no_grad():
        out = model(data.x, data.edge_index).squeeze()
        probs = torch.sigmoid(out)
        test_probs = probs[data.test_mask].cpu().numpy()
        test_y = data.y[data.test_mask].cpu().numpy()

    # pull standard metrics
    auc_roc = roc_auc_score(test_y, test_probs) if len(np.unique(test_y)) > 1 else 0.0
    auc_pr = average_precision_score(test_y, test_probs) if len(np.unique(test_y)) > 1 else 0.0
    print(f"AUC-ROC: {auc_roc:.4f} | AUC-PR: {auc_pr:.4f}")

## GCN (Graph Convolutional Network) Model

We define the `FraudGCN` model architecture, utilizing standard Graph Convolutional layers (`GCNConv`) with dropout for regularization.

In [42]:
class FraudGCN(torch.nn.Module):
    def __init__(self, in_channels, hidden_channels, out_channels):
        super(FraudGCN, self).__init__()
        self.conv1 = GCNConv(in_channels, hidden_channels)
        self.conv2 = GCNConv(hidden_channels, out_channels)

    def forward(self, x, edge_index):
        x = self.conv1(x, edge_index)
        x = F.relu(x)
        x = F.dropout(x, p=0.5, training=self.training)
        x = self.conv2(x, edge_index)
        return x

## GAT (Graph Attention Networks) Model

We define the `FraudGAT` model. This model uses multi-head graph attention mechanisms (`GATConv`) to weigh neighboring nodes differently based on their features.

In [43]:
class FraudGAT(torch.nn.Module):
    def __init__(self, in_channels, hidden_channels, out_channels, heads=4):
        super(FraudGAT, self).__init__()
        self.conv1 = GATConv(in_channels, hidden_channels // heads, heads=heads)
        self.conv2 = GATConv(hidden_channels, out_channels, heads=1, concat=False)

    def forward(self, x, edge_index):
        x = self.conv1(x, edge_index)
        x = F.elu(x)
        x = F.dropout(x, p=0.5, training=self.training)
        x = self.conv2(x, edge_index)
        return x

## Threshold Tuning Strategy
Since fraud detection involves highly imbalanced classes, standard evaluation metrics like Accuracy are misleading. The function below evaluates our models by sweeping across different probability thresholds to maximize the F1-score specifically for the minority (fraud) class.

In [47]:
def tune_model_threshold(model, data, dataset_name, weight):
    print(f"\n{'-'*15} Tuning Thresholds: {dataset_name} (Weight: {weight}) {'-'*15}")
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

    model.eval()
    model.to(device)
    data = data.to(device)

    with torch.no_grad():
        out = model(data.x, data.edge_index).squeeze()
        probs = torch.sigmoid(out[data.test_mask]).cpu().numpy()
        y_true = data.y[data.test_mask].cpu().numpy()

    auc_pr = average_precision_score(y_true, probs) if len(np.unique(y_true)) > 1 else 0.0
    print(f"AUC-PR: {auc_pr:.4f}")

    thresholds = np.linspace(0.01, 0.99, 50)
    best_f1 = 0
    best_metrics = {}

    for t in thresholds:
        preds = (probs > t).astype(float)
        report = classification_report(y_true, preds, output_dict=True, zero_division=0)
        f1_pos = report['1.0']['f1-score']

        if f1_pos > best_f1:
            best_f1 = f1_pos
            best_metrics = {
                'AUC-PR': auc_pr,
                'Threshold': t,
                'Weight': weight,
                'Accuracy': report['accuracy'],
                'Recall': report['1.0']['recall'],
                'F1 (Macro)': report['macro avg']['f1-score'],
                'F1 (Weighted)': report['weighted avg']['f1-score'],
                'Precision': report['1.0']['precision'],
                'F1 (Pos)': f1_pos
            }

    if best_metrics:
        print(f"> Best Threshold: {best_metrics['Threshold']:.2f} | Best F1 (Pos): {best_f1:.4f}")
        print(f"> Precision: {best_metrics['Precision']:.4f} | Recall: {best_metrics['Recall']:.4f} | F1 (Macro): {best_metrics['F1 (Macro)']:.4f}")

    return best_f1, best_metrics

## Pipeline Executions

### GraphSAGE Pipeline
We now execute the end-to-end training and tuning pipeline for GraphSAGE across all three datasets (PaySim, IEEE-CIS, and Elliptic). For each dataset, we perform a search over `pos_weight` values to find the best configuration.

In [48]:
def run_sage_pipeline(dataset_name, nodes_path, edges_path, target_col):
    print(f"\n{'='*40}\n Processing {dataset_name} \n{'='*40}")
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

    # Load data once
    data, _ = load_graph_data(nodes_path, edges_path, target_col)

    best_overall_f1 = 0
    best_model = None
    best_model_metrics = None

    # Grid search for pos_weight
    for w in [5, 10, 20, 50]:
        print(f"\n--- Training GraphSAGE with pos_weight = {w} ---")
        model = FraudGraphSAGE(data.num_features, 128, 1)
        weight_tensor = torch.tensor([w], dtype=torch.float)

        train_gnn(model, data, weight_tensor, device, epochs=300, patience=20)
        f1, metrics = tune_model_threshold(model, data, dataset_name, w)

        if f1 > best_overall_f1:
            best_overall_f1 = f1
            best_model = model
            best_model_metrics = metrics

    print(f"\n{'='*40}")
    print(f"BEST {dataset_name} GraphSAGE MODEL RESULTS:")
    if best_model_metrics:
        print(f"Weight: {best_model_metrics['Weight']}")
        print(f"Threshold: {best_model_metrics['Threshold']:.2f}")
        print(f"AUC-PR: {best_model_metrics['AUC-PR']:.4f}")
        print(f"Accuracy: {best_model_metrics['Accuracy']:.4f}")
        print(f"Recall: {best_model_metrics['Recall']:.4f}")
        print(f"F1 (Pos): {best_model_metrics['F1 (Pos)']:.4f}")
        print(f"F1 (Macro): {best_model_metrics['F1 (Macro)']:.4f}")
        print(f"F1 (Weighted): {best_model_metrics['F1 (Weighted)']:.4f}")
    print(f"{'='*40}")
    return best_model

# Retrain GraphSAGE for all three datasets with pos_weight tuning
paysim_sage_model = run_sage_pipeline(
    "PaySim",
    "/content/data/processed/paysim_nodes.csv",
    "/content/data/processed/paysim_edges.csv",
    "label"
)

ieee_sage_model = run_sage_pipeline(
    "IEEE-CIS",
    "/content/data/processed/ieee_train_nodes.csv",
    "/content/data/processed/ieee_train_edges.csv",
    "label"
)

elliptic_sage_model = run_sage_pipeline(
    "Elliptic",
    "/content/data/processed/elliptic_nodes.csv",
    "/content/data/processed/elliptic_edges.csv",
    "label"
)

========================================
 Processing PaySim
========================================
Loading graph data...

--- Training GraphSAGE with pos_weight = 5 ---
Epoch 050/300 | Loss: 0.0366
Epoch 100/300 | Loss: 0.0309
Epoch 150/300 | Loss: 0.0280
Epoch 200/300 | Loss: 0.0265
Epoch 250/300 | Loss: 0.0255
Epoch 300/300 | Loss: 0.0250

--------------- Tuning Thresholds: PaySim (Weight: 5) ---------------
AUC-PR: 0.4249
> Best Threshold: 0.21 | Best F1 (Pos): 0.4806
> Precision: 0.7313 | Recall: 0.3579 | F1 (Macro): 0.7400

--- Training GraphSAGE with pos_weight = 10 ---
Epoch 050/300 | Loss: 0.0580
Epoch 100/300 | Loss: 0.0486
Epoch 150/300 | Loss: 0.0442
Epoch 200/300 | Loss: 0.0416
Epoch 250/300 | Loss: 0.0399
Epoch 300/300 | Loss: 0.0387

--------------- Tuning Thresholds: PaySim (Weight: 10) ---------------
AUC-PR: 0.4890
> Best Threshold: 0.33 | Best F1 (Pos): 0.5361
> Precision: 0.7691 | Recall: 0.4114 | F1 (Macro): 0.7678

--- Training GraphSAGE with pos_weight = 20 ---
Epoch 050/300 | Loss: 0.0926
Epoch 100/300 | Loss: 0.0745
Epoch 150/300 | Loss: 0.0658
Epoch 200/300 | Loss: 0.0616
Epoch 250/300 | Loss: 0.0591
Epoch 300/300 | Loss: 0.0572

--------------- Tuning Thresholds: PaySim (Weight: 20) ---------------
AUC-PR: 0.5427
> Best Threshold: 0.57 | Best F1 (Pos): 0.5819
> Precision: 0.9174 | Recall: 0.4260 | F1 (Macro): 0.7907

--- Training GraphSAGE with pos_weight = 50 ---
Epoch 050/300 | Loss: 0.1568
Epoch 100/300 | Loss: 0.1264
Epoch 150/300 | Loss: 0.1133
Epoch 200/300 | Loss: 0.1042
Epoch 250/300 | Loss: 0.0986
Epoch 300/300 | Loss: 0.0934

--------------- Tuning Thresholds: PaySim (Weight: 50) ---------------
AUC-PR: 0.5937
> Best Threshold: 0.71 | Best F1 (Pos): 0.6090
> Precision: 0.7652 | Recall: 0.5058 | F1 (Macro): 0.8043

========================================
BEST PaySim GraphSAGE MODEL RESULTS:
Weight: 50
Threshold: 0.71
AUC-PR: 0.5937
Accuracy: 0.9992
Recall: 0.5058
F1 (Pos): 0.6090
F1 (Macro): 0.8043
F1 (Weighted): 0.9991
========================================

========================================
 Processing IEEE-CIS
========================================
Loading graph data...

--- Training GraphSAGE with pos_weight = 5 ---
Epoch 050/300 | Loss: 0.3125
Epoch 100/300 | Loss: 0.2930
Epoch 150/300 | Loss: 0.2731
Epoch 200/300 | Loss: 0.2654
Epoch 250/300 | Loss: 0.2691
Early stopping at epoch 262 (Loss: 0.2677)

--------------- Tuning Thresholds: IEEE-CIS (Weight: 5) ---------------
AUC-PR: 0.5655
> Best Threshold: 0.47 | Best F1 (Pos): 0.5529
> Precision: 0.6649 | Recall: 0.4733 | F1 (Macro): 0.7696

--- Training GraphSAGE with pos_weight = 10 ---
Epoch 050/300 | Loss: 0.4742
Epoch 100/300 | Loss: 0.4315
Early stopping at epoch 145 (Loss: 0.4142)

--------------- Tuning Thresholds: IEEE-CIS (Weight: 10) ---------------
AUC-PR: 0.5421
> Best Threshold: 0.73 | Best F1 (Pos): 0.5331
> Precision: 0.6458 | Recall: 0.4539 | F1 (Macro): 0.7594

--- Training GraphSAGE with pos_weight = 20 ---
Epoch 050/300 | Loss: 0.7070
Epoch 100/300 | Loss: 0.6356
Epoch 150/300 | Loss: 0.5936
Epoch 200/300 | Loss: 0.5644
Epoch 250/300 | Loss: 0.5621
Early stopping at epoch 264 (Loss: 0.5372)

--------------- Tuning Thresholds: IEEE-CIS (Weight: 20) ---------------
AUC-PR: 0.5592
> Best Threshold: 0.81 | Best F1 (Pos): 0.5399
> Precision: 0.6246 | Recall: 0.4754 | F1 (Macro): 0.7626

--- Training GraphSAGE with pos_weight = 50 ---
Epoch 050/300 | Loss: 1.1561
Epoch 100/300 | Loss: 1.0509
Epoch 150/300 | Loss: 0.9806
Epoch 200/300 | Loss: 0.9573
Epoch 250/300 | Loss: 0.9448
Early stopping at epoch 264 (Loss: 0.8766)

--------------- Tuning Thresholds: IEEE-CIS (Weight: 50) ---------------
AUC-PR: 0.5473
> Best Threshold: 0.91 | Best F1 (Pos): 0.5276
> Precision: 0.6012 | Recall: 0.4701 | F1 (Macro): 0.7562

========================================
BEST IEEE-CIS GraphSAGE MODEL RESULTS:
Weight: 5
Threshold: 0.47
AUC-PR: 0.5655
Accuracy: 0.9732
Recall: 0.4733
F1 (Pos): 0.5529
F1 (Macro): 0.7696
F1 (Weighted): 0.9710
========================================

========================================
 Processing Elliptic
========================================
Loading graph data...
Warning: Duplicate node IDs found in 'tx_id'. Keeping first.

--- Training GraphSAGE with pos_weight = 5 ---
Epoch 050/300 | Loss: 0.1264
Epoch 100/300 | Loss: 0.0748
Early stopping at epoch 144 (Loss: 0.0719)

--------------- Tuning Thresholds: Elliptic (Weight: 5) ---------------
AUC-PR: 0.8736
> Best Threshold: 0.65 | Best F1 (Pos): 0.8365
> Precision: 0.8966 | Recall: 0.7839 | F1 (Macro): 0.9105

--- Training GraphSAGE with pos_weight = 10 ---
Epoch 050/300 | Loss: 0.1775
Epoch 100/300 | Loss: 0.1012
Epoch 150/300 | Loss: 0.0799
Early stopping at epoch 164 (Loss: 0.0931)

--------------- Tuning Thresholds: Elliptic (Weight: 10) ---------------
AUC-PR: 0.8706
> Best Threshold: 0.89 | Best F1 (Pos): 0.8441
> Precision: 0.9075 | Recall: 0.7889 | F1 (Macro): 0.9147

--- Training GraphSAGE with pos_weight = 20 ---
Epoch 050/300 | Loss: 0.2771
Epoch 100/300 | Loss: 0.1536
Early stopping at epoch 146 (Loss: 0.1410)

--------------- Tuning Thresholds: Elliptic (Weight: 20) ---------------
AUC-PR: 0.8485
> Best Threshold: 0.95 | Best F1 (Pos): 0.8293
> Precision: 0.9000 | Recall: 0.7688 | F1 (Macro): 0.9066

--- Training GraphSAGE with pos_weight = 50 ---
Epoch 050/300 | Loss: 0.4953
Epoch 100/300 | Loss: 0.2908
Epoch 150/300 | Loss: 0.2089
Epoch 200/300 | Loss: 0.1800
Early stopping at epoch 227 (Loss: 0.2439)

--------------- Tuning Thresholds: Elliptic (Weight: 50) ---------------
AUC-PR: 0.8298
> Best Threshold: 0.97 | Best F1 (Pos): 0.8033
> Precision: 0.8802 | Recall: 0.7387 | F1 (Macro): 0.8925

========================================
BEST Elliptic GraphSAGE MODEL RESULTS:
Weight: 10
Threshold: 0.89
AUC-PR: 0.8706
Accuracy: 0.9730
Recall: 0.7889
F1 (Pos): 0.8441
F1 (Macro): 0.9147
F1 (Weighted): 0.9722
========================================

### GCN Pipeline
Similarly, we run the evaluation pipeline using the GCN model on all three datasets to compare against the GraphSAGE benchmark.

In [49]:
from torch_geometric.nn import GCNConv

def run_gcn_pipeline(dataset_name, nodes_path, edges_path, target_col):
    print(f"\n{'='*40}\n Processing {dataset_name} (GCN)\n{'='*40}")
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

    # Load data once
    data, _ = load_graph_data(nodes_path, edges_path, target_col)

    best_overall_f1 = 0
    best_model = None
    best_model_metrics = None

    # Grid search for pos_weight
    for w in [5, 10, 20, 50]:
        print(f"\n--- Training GCN with pos_weight = {w} ---")
        model = FraudGCN(data.num_features, 128, 1)
        weight_tensor = torch.tensor([w], dtype=torch.float)

        train_gnn(model, data, weight_tensor, device, epochs=300, patience=20)
        f1, metrics = tune_model_threshold(model, data, f"{dataset_name} (GCN)", w)

        if f1 > best_overall_f1:
            best_overall_f1 = f1
            best_model = model
            best_model_metrics = metrics

    print(f"\n{'='*40}")
    print(f"BEST {dataset_name} GCN MODEL RESULTS:")
    if best_model_metrics:
        print(f"Weight: {best_model_metrics['Weight']}")
        print(f"Threshold: {best_model_metrics['Threshold']:.2f}")
        print(f"AUC-PR: {best_model_metrics['AUC-PR']:.4f}")
        print(f"Accuracy: {best_model_metrics['Accuracy']:.4f}")
        print(f"Recall: {best_model_metrics['Recall']:.4f}")
        print(f"F1 (Pos): {best_model_metrics['F1 (Pos)']:.4f}")
        print(f"F1 (Macro): {best_model_metrics['F1 (Macro)']:.4f}")
        print(f"F1 (Weighted): {best_model_metrics['F1 (Weighted)']:.4f}")
    print(f"{'='*40}")
    return best_model

# Retrain GCN for all three datasets with pos_weight tuning
paysim_gcn_model = run_gcn_pipeline(
    "PaySim",
    "/content/data/processed/paysim_nodes.csv",
    "/content/data/processed/paysim_edges.csv",
    "label"
)

ieee_gcn_model = run_gcn_pipeline(
    "IEEE-CIS",
    "/content/data/processed/ieee_train_nodes.csv",
    "/content/data/processed/ieee_train_edges.csv",
    "label"
)

elliptic_gcn_model = run_gcn_pipeline(
    "Elliptic",
    "/content/data/processed/elliptic_nodes.csv",
    "/content/data/processed/elliptic_edges.csv",
    "label"
)

========================================
 Processing PaySim (GCN)
========================================
Loading graph data...

--- Training GCN with pos_weight = 5 ---
Epoch 050/300 | Loss: 0.0382
Epoch 100/300 | Loss: 0.0336
Epoch 150/300 | Loss: 0.0320
Epoch 200/300 | Loss: 0.0309
Epoch 250/300 | Loss: 0.0303
Epoch 300/300 | Loss: 0.0298

--------------- Tuning Thresholds: PaySim (GCN) (Weight: 5) ---------------
AUC-PR: 0.1757
> Best Threshold: 0.27 | Best F1 (Pos): 0.2604
> Precision: 0.3660 | Recall: 0.2021 | F1 (Macro): 0.6298

--- Training GCN with pos_weight = 10 ---
Epoch 050/300 | Loss: 0.0597
Epoch 100/300 | Loss: 0.0546
Epoch 150/300 | Loss: 0.0522
Epoch 200/300 | Loss: 0.0509
Epoch 250/300 | Loss: 0.0501
Epoch 300/300 | Loss: 0.0496

--------------- Tuning Thresholds: PaySim (GCN) (Weight: 10) ---------------
AUC-PR: 0.2153
> Best Threshold: 0.45 | Best F1 (Pos): 0.2933
> Precision: 0.4123 | Recall: 0.2276 | F1 (Macro): 0.6463

--- Training GCN with pos_weight = 20 ---
Epoch 050/300 | Loss: 0.0971
Epoch 100/300 | Loss: 0.0907
Epoch 150/300 | Loss: 0.0871
Epoch 200/300 | Loss: 0.0847
Epoch 250/300 | Loss: 0.0835
Epoch 300/300 | Loss: 0.0828

--------------- Tuning Thresholds: PaySim (GCN) (Weight: 20) ---------------
AUC-PR: 0.2394
> Best Threshold: 0.69 | Best F1 (Pos): 0.3122
> Precision: 0.4967 | Recall: 0.2276 | F1 (Macro): 0.6558

--- Training GCN with pos_weight = 50 ---
Epoch 050/300 | Loss: 0.1803
Epoch 100/300 | Loss: 0.1690
Epoch 150/300 | Loss: 0.1628
Epoch 200/300 | Loss: 0.1586
Epoch 250/300 | Loss: 0.1556
Epoch 300/300 | Loss: 0.1531

--------------- Tuning Thresholds: PaySim (GCN) (Weight: 50) ---------------
AUC-PR: 0.2735
> Best Threshold: 0.83 | Best F1 (Pos): 0.3598
> Precision: 0.5560 | Recall: 0.2660 | F1 (Macro): 0.6796

========================================
BEST PaySim GCN MODEL RESULTS:
Weight: 50
Threshold: 0.83
AUC-PR: 0.2735
Accuracy: 0.9988
Recall: 0.2660
F1 (Pos): 0.3598
F1 (Macro): 0.6796
F1 (Weighted): 0.9986
========================================

========================================
 Processing IEEE-CIS (GCN)
========================================
Loading graph data...

--- Training GCN with pos_weight = 5 ---
Epoch 050/300 | Loss: 0.4106
Epoch 100/300 | Loss: 0.4027
Epoch 150/300 | Loss: 0.4005
Epoch 200/300 | Loss: 0.3946
Early stopping at epoch 232 (Loss: 0.3943)

--------------- Tuning Thresholds: IEEE-CIS (GCN) (Weight: 5) ---------------
AUC-PR: 0.2469
> Best Threshold: 0.41 | Best F1 (Pos): 0.2943
> Precision: 0.3305 | Recall: 0.2652 | F1 (Macro): 0.6356

--- Training GCN with pos_weight = 10 ---
Epoch 050/300 | Loss: 0.6341
Epoch 100/300 | Loss: 0.6200
Epoch 150/300 | Loss: 0.6111
Early stopping at epoch 182 (Loss: 0.6113)

--------------- Tuning Thresholds: IEEE-CIS (GCN) (Weight: 10) ---------------
AUC-PR: 0.2386
> Best Threshold: 0.65 | Best F1 (Pos): 0.2842
> Precision: 0.3102 | Recall: 0.2623 | F1 (Macro): 0.6302

--- Training GCN with pos_weight = 20 ---
Epoch 050/300 | Loss: 0.9493
Epoch 100/300 | Loss: 0.9254
Epoch 150/300 | Loss: 0.9100
Epoch 200/300 | Loss: 0.9019
Epoch 250/300 | Loss: 0.8880
Early stopping at epoch 278 (Loss: 0.8843)

--------------- Tuning Thresholds: IEEE-CIS (GCN) (Weight: 20) ---------------
AUC-PR: 0.2430
> Best Threshold: 0.69 | Best F1 (Pos): 0.2925
> Precision: 0.3141 | Recall: 0.2737 | F1 (Macro): 0.6343

--- Training GCN with pos_weight = 50 ---
Epoch 050/300 | Loss: 1.5134
Epoch 100/300 | Loss: 1.4762
Epoch 150/300 | Loss: 1.4502
Epoch 200/300 | Loss: 1.4307
Epoch 250/300 | Loss: 1.4203
Epoch 300/300 | Loss: 1.3975

--------------- Tuning Thresholds: IEEE-CIS (GCN) (Weight: 50) ---------------
AUC-PR: 0.2426
> Best Threshold: 0.87 | Best F1 (Pos): 0.2896
> Precision: 0.2915 | Recall: 0.2877 | F1 (Macro): 0.6320

========================================
BEST IEEE-CIS GCN MODEL RESULTS:
Weight: 5
Threshold: 0.41
AUC-PR: 0.2469
Accuracy: 0.9555
Recall: 0.2652
F1 (Pos): 0.2943
F1 (Macro): 0.6356
F1 (Weighted): 0.9531
========================================

========================================
 Processing Elliptic (GCN)
========================================
Loading graph data...
Warning: Duplicate node IDs found in 'tx_id'. Keeping first.

--- Training GCN with pos_weight = 5 ---
Epoch 050/300 | Loss: 0.5247
Epoch 100/300 | Loss: 0.4559
Epoch 150/300 | Loss: 0.4080
Epoch 200/300 | Loss: 0.3892
Epoch 250/300 | Loss: 0.3617
Early stopping at epoch 272 (Loss: 0.3539)

--------------- Tuning Thresholds: Elliptic (GCN) (Weight: 5) ---------------
AUC-PR: 0.4652
> Best Threshold: 0.81 | Best F1 (Pos): 0.5519
> Precision: 0.6739 | Recall: 0.4673 | F1 (Macro): 0.7569

--- Training GCN with pos_weight = 10 ---
Epoch 050/300 | Loss: 0.6973
Epoch 100/300 | Loss: 0.5721
Epoch 150/300 | Loss: 0.5206
Epoch 200/300 | Loss: 0.4786
Epoch 250/300 | Loss: 0.4533
Early stopping at epoch 293 (Loss: 0.4125)

--------------- Tuning Thresholds: Elliptic (GCN) (Weight: 10) ---------------
AUC-PR: 0.4721
> Best Threshold: 0.89 | Best F1 (Pos): 0.5486
> Precision: 0.6358 | Recall: 0.4824 | F1 (Macro): 0.7543

--- Training GCN with pos_weight = 20 ---
Epoch 050/300 | Loss: 1.0165
Epoch 100/300 | Loss: 0.8343
Epoch 150/300 | Loss: 0.7267
Early stopping at epoch 182 (Loss: 0.6948)

--------------- Tuning Thresholds: Elliptic (GCN) (Weight: 20) ---------------
AUC-PR: 0.4345
> Best Threshold: 0.93 | Best F1 (Pos): 0.5385
> Precision: 0.6547 | Recall: 0.4573 | F1 (Macro): 0.7496

--- Training GCN with pos_weight = 50 ---
Epoch 050/300 | Loss: 1.4788
Epoch 100/300 | Loss: 1.2081
Epoch 150/300 | Loss: 1.0895
Early stopping at epoch 197 (Loss: 0.9961)

--------------- Tuning Thresholds: Elliptic (GCN) (Weight: 50) ---------------
AUC-PR: 0.4283
> Best Threshold: 0.95 | Best F1 (Pos): 0.5344
> Precision: 0.5412 | Recall: 0.5276 | F1 (Macro): 0.7438

========================================
BEST Elliptic GCN MODEL RESULTS:
Weight: 5
Threshold: 0.81
AUC-PR: 0.4652
Accuracy: 0.9298
Recall: 0.4673
F1 (Pos): 0.5519
F1 (Macro): 0.7569
F1 (Weighted): 0.9240
========================================

### GAT Pipeline
Finally, we evaluate the Graph Attention Network (GAT) model across the datasets, searching for the optimal class weight and threshold combination.

In [59]:
import gc
import copy
from torch_geometric.nn import GATConv

def run_gat_pipeline(dataset_name, nodes_path, edges_path, target_col):
    print(f"\n{'='*40}\n Processing {dataset_name} (GAT)\n{'='*40}")
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

    # Load data once
    data, _ = load_graph_data(nodes_path, edges_path, target_col)

    best_overall_f1 = 0
    best_model = None
    best_model_metrics = None

    # Grid search for pos_weight
    for w in [5, 10, 20, 50]:
        print(f"\n--- Training GAT with pos_weight = {w} ---")
        model = FraudGAT(data.num_features, 32, 1, heads=2)
        weight_tensor = torch.tensor([w], dtype=torch.float)

        train_gnn(model, data, weight_tensor, device, epochs=300, patience=20)
        f1, metrics = tune_model_threshold(model, data, f"{dataset_name} (GAT)", w)

        if f1 > best_overall_f1:
            best_overall_f1 = f1
            # Move the best model to CPU to free up GPU memory
            best_model = copy.deepcopy(model).cpu()
            best_model_metrics = metrics

        # Aggressive memory cleanup after every single weight iteration
        del model
        del weight_tensor
        gc.collect()
        if torch.cuda.is_available():
            torch.cuda.empty_cache()

    print(f"\n{'='*40}")
    print(f"BEST {dataset_name} GAT MODEL RESULTS:")
    if best_model_metrics:
        print(f"Weight: {best_model_metrics['Weight']}")
        print(f"Threshold: {best_model_metrics['Threshold']:.2f}")
        print(f"AUC-PR: {best_model_metrics['AUC-PR']:.4f}")
        print(f"Accuracy: {best_model_metrics['Accuracy']:.4f}")
        print(f"Recall: {best_model_metrics['Recall']:.4f}")
        print(f"F1 (Pos): {best_model_metrics['F1 (Pos)']:.4f}")
        print(f"F1 (Macro): {best_model_metrics['F1 (Macro)']:.4f}")
        print(f"F1 (Weighted): {best_model_metrics['F1 (Weighted)']:.4f}")
    print(f"{'='*40}")

    # Cleanup dataset memory before moving to the next dataset
    del data
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

    return best_model

# Retrain GAT for all three datasets with pos_weight tuning
paysim_gat_model = run_gat_pipeline(
    "PaySim",
    "/content/data/processed/paysim_nodes.csv",
    "/content/data/processed/paysim_edges.csv",
    "label"
)

ieee_gat_model = run_gat_pipeline(
    "IEEE-CIS",
    "/content/data/processed/ieee_train_nodes.csv",
    "/content/data/processed/ieee_train_edges.csv",
    "label"
)

elliptic_gat_model = run_gat_pipeline(
    "Elliptic",
    "/content/data/processed/elliptic_nodes.csv",
    "/content/data/processed/elliptic_edges.csv",
    "label"
)

========================================
 Processing PaySim (GAT)
========================================
Loading graph data...

--- Training GAT with pos_weight = 5 ---
Epoch 050/300 | Loss: 0.0497
Epoch 100/300 | Loss: 0.0396
Epoch 150/300 | Loss: 0.0351
Epoch 200/300 | Loss: 0.0329
Epoch 250/300 | Loss: 0.0317
Epoch 300/300 | Loss: 0.0308

--------------- Tuning Thresholds: PaySim (GAT) (Weight: 5) ---------------
AUC-PR: 0.0831
> Best Threshold: 0.43 | Best F1 (Pos): 0.1996
> Precision: 0.2396 | Recall: 0.1710 | F1 (Macro): 0.5993

--- Training GAT with pos_weight = 10 ---
Epoch 050/300 | Loss: 0.0673
Epoch 100/300 | Loss: 0.0587
Epoch 150/300 | Loss: 0.0547
Epoch 200/300 | Loss: 0.0518
Epoch 250/300 | Loss: 0.0499
Epoch 300/300 | Loss: 0.0485

--------------- Tuning Thresholds: PaySim (GAT) (Weight: 10) ---------------
AUC-PR: 0.1659
> Best Threshold: 0.57 | Best F1 (Pos): 0.2556
> Precision: 0.2875 | Recall: 0.2301 | F1 (Macro): 0.6274

--- Training GAT with pos_weight = 20 ---
Epoch 050/300 | Loss: 0.1052
Epoch 100/300 | Loss: 0.0915
Epoch 150/300 | Loss: 0.0851
Epoch 200/300 | Loss: 0.0819
Epoch 250/300 | Loss: 0.0798
Epoch 300/300 | Loss: 0.0781

--------------- Tuning Thresholds: PaySim (GAT) (Weight: 20) ---------------
AUC-PR: 0.1577
> Best Threshold: 0.71 | Best F1 (Pos): 0.2574
> Precision: 0.2473 | Recall: 0.2684 | F1 (Macro): 0.6282

--- Training GAT with pos_weight = 50 ---
Epoch 050/300 | Loss: 0.1781
Epoch 100/300 | Loss: 0.1554
Epoch 150/300 | Loss: 0.1447
Epoch 200/300 | Loss: 0.1390
Epoch 250/300 | Loss: 0.1347
Epoch 300/300 | Loss: 0.1314

--------------- Tuning Thresholds: PaySim (GAT) (Weight: 50) ---------------
AUC-PR: 0.1911
> Best Threshold: 0.89 | Best F1 (Pos): 0.2934
> Precision: 0.2865 | Recall: 0.3007 | F1 (Macro): 0.6463

========================================
BEST PaySim GAT MODEL RESULTS:
Weight: 50
Threshold: 0.89
AUC-PR: 0.1911
Accuracy: 0.9981
Recall: 0.3007
F1 (Pos): 0.2934
F1 (Macro): 0.6463
F1 (Weighted): 0.9982
========================================

========================================
 Processing IEEE-CIS (GAT)
========================================
Loading graph data...

--- Training GAT with pos_weight = 5 ---
Epoch 050/300 | Loss: 0.4230
Epoch 100/300 | Loss: 0.4080
Epoch 150/300 | Loss: 0.3994
Epoch 200/300 | Loss: 0.3956
Epoch 250/300 | Loss: 0.3935
Epoch 300/300 | Loss: 0.3911

--------------- Tuning Thresholds: IEEE-CIS (GAT) (Weight: 5) ---------------
AUC-PR: 0.2544
> Best Threshold: 0.45 | Best F1 (Pos): 0.2953
> Precision: 0.2905 | Recall: 0.3003 | F1 (Macro): 0.6347

--- Training GAT with pos_weight = 10 ---
Epoch 050/300 | Loss: 0.6453
Epoch 100/300 | Loss: 0.6255
Epoch 150/300 | Loss: 0.6115
Epoch 200/300 | Loss: 0.5998
Epoch 250/300 | Loss: 0.5923
Epoch 300/300 | Loss: 0.5867

--------------- Tuning Thresholds: IEEE-CIS (GAT) (Weight: 10) ---------------
AUC-PR: 0.2711
> Best Threshold: 0.63 | Best F1 (Pos): 0.3350
> Precision: 0.3334 | Recall: 0.3366 | F1 (Macro): 0.6554

--- Training GAT with pos_weight = 20 ---
Epoch 050/300 | Loss: 0.9904
Epoch 100/300 | Loss: 0.9359
Epoch 150/300 | Loss: 0.9017
Epoch 200/300 | Loss: 0.8760
Epoch 250/300 | Loss: 0.8582
Epoch 300/300 | Loss: 0.8523

--------------- Tuning Thresholds: IEEE-CIS (GAT) (Weight: 20) ---------------
AUC-PR: 0.2630
> Best Threshold: 0.77 | Best F1 (Pos): 0.3419
> Precision: 0.3384 | Recall: 0.3455 | F1 (Macro): 0.6589

--- Training GAT with pos_weight = 50 ---
Epoch 050/300 | Loss: 1.5058
Epoch 100/300 | Loss: 1.4678
Epoch 150/300 | Loss: 1.4436
Epoch 200/300 | Loss: 1.4301
Epoch 250/300 | Loss: 1.4186
Early stopping at epoch 295 (Loss: 1.4105)

--------------- Tuning Thresholds: IEEE-CIS (GAT) (Weight: 50) ---------------
AUC-PR: 0.2303
> Best Threshold: 0.89 | Best F1 (Pos): 0.2728
> Precision: 0.2566 | Recall: 0.2913 | F1 (Macro): 0.6223

========================================
BEST IEEE-CIS GAT MODEL RESULTS:
Weight: 20
Threshold: 0.77
AUC-PR: 0.2630
Accuracy: 0.9535
Recall: 0.3455
F1 (Pos): 0.3419
F1 (Macro): 0.6589
F1 (Weighted): 0.9537
========================================

========================================
 Processing Elliptic (GAT)
========================================
Loading graph data...
Warning: Duplicate node IDs found in 'tx_id'. Keeping first.

--- Training GAT with pos_weight = 5 ---
Epoch 050/300 | Loss: 0.6026
Epoch 100/300 | Loss: 0.5180
Epoch 150/300 | Loss: 0.4841
Epoch 200/300 | Loss: 0.4455
Epoch 250/300 | Loss: 0.4363
Early stopping at epoch 268 (Loss: 0.4362)

--------------- Tuning Thresholds: Elliptic (GAT) (Weight: 5) ---------------
AUC-PR: 0.5199
> Best Threshold: 0.73 | Best F1 (Pos): 0.5469
> Precision: 0.5862 | Recall: 0.5126 | F1 (Macro): 0.7520

--- Training GAT with pos_weight = 10 ---
Epoch 050/300 | Loss: 0.9095
Epoch 100/300 | Loss: 0.6661
Epoch 150/300 | Loss: 0.5382
Epoch 200/300 | Loss: 0.4885
Early stopping at epoch 235 (Loss: 0.4775)

--------------- Tuning Thresholds: Elliptic (GAT) (Weight: 10) ---------------
AUC-PR: 0.5614
> Best Threshold: 0.81 | Best F1 (Pos): 0.6178
> Precision: 0.5672 | Recall: 0.6784 | F1 (Macro): 0.7873

--- Training GAT with pos_weight = 20 ---
Epoch 050/300 | Loss: 0.9046
Epoch 100/300 | Loss: 0.7527
Epoch 150/300 | Loss: 0.7003
Epoch 200/300 | Loss: 0.6068
Epoch 250/300 | Loss: 0.5743
Early stopping at epoch 270 (Loss: 0.5753)

--------------- Tuning Thresholds: Elliptic (GAT) (Weight: 20) ---------------
AUC-PR: 0.5972
> Best Threshold: 0.91 | Best F1 (Pos): 0.6606
> Precision: 0.6008 | Recall: 0.7337 | F1 (Macro): 0.8109

--- Training GAT with pos_weight = 50 ---
Epoch 050/300 | Loss: 1.3378
Epoch 100/300 | Loss: 1.0766
Epoch 150/300 | Loss: 0.9144
Early stopping at epoch 186 (Loss: 0.8997)

--------------- Tuning Thresholds: Elliptic (GAT) (Weight: 50) ---------------
AUC-PR: 0.5551
> Best Threshold: 0.97 | Best F1 (Pos): 0.6283
> Precision: 0.6009 | Recall: 0.6583 | F1 (Macro): 0.7942

========================================
BEST Elliptic GAT MODEL RESULTS:
Weight: 20
Threshold: 0.91
AUC-PR: 0.5972
Accuracy: 0.9303
Recall: 0.7337
F1 (Pos): 0.6606
F1 (Macro): 0.8109
F1 (Weighted): 0.9334
========================================

In [58]:
import gc
import torch

print("Starting aggressive garbage collection...")

# Run garbage collection multiple times to catch circular references
for _ in range(3):
    gc.collect()

# Empty PyTorch's CUDA cache and IPC to free up GPU memory
if torch.cuda.is_available():
    torch.cuda.empty_cache()
    torch.cuda.ipc_collect()
    print("\n--- GPU Memory Status ---")
    print(torch.cuda.memory_summary(abbreviated=True))
    print("CUDA cache and IPC cleared.")

print("Aggressive garbage collection complete. Ready for GAT pipeline!")

Starting aggressive garbage collection...

--- GPU Memory Status ---
|===========================================================================|
|                  PyTorch CUDA memory summary, device ID 0                 |
|---------------------------------------------------------------------------|
|            CUDA OOMs: 4            |        cudaMalloc retries: 6         |
|===========================================================================|
|        Metric         | Cur Usage  | Peak Usage | Tot Alloc  | Tot Freed  |
|---------------------------------------------------------------------------|
| Allocated memory      |   7682 MiB |  89094 MiB | 643151 GiB | 643144 GiB |
|---------------------------------------------------------------------------|
| Active memory         |   7682 MiB |  89094 MiB | 643151 GiB | 643144 GiB |
|---------------------------------------------------------------------------|
| Requested memory      |   7682 MiB |  89093 MiB | 643120 GiB | 643113 GiB |
|---------------------------------------------------------------------------|
| GPU reserved memory   |  55338 MiB |  95022 MiB | 237262 MiB | 181924 MiB |
|---------------------------------------------------------------------------|
| Non-releasable memory |  47655 MiB |  70048 MiB | 504997 GiB | 504951 GiB |
|---------------------------------------------------------------------------|
| Allocations           |     337    |     414    |    1691 K  |    1691 K  |
|---------------------------------------------------------------------------|
| Active allocs         |     337    |     414    |    1691 K  |    1691 K  |
|---------------------------------------------------------------------------|
| GPU reserved segments |      11    |      25    |      33    |      22    |
|---------------------------------------------------------------------------|
| Non-releasable allocs |      38    |      47    |  588581    |  588543    |
|---------------------------------------------------------------------------|
| Oversize allocations  |       0    |       0    |       0    |       0    |
|---------------------------------------------------------------------------|
| Oversize GPU segments |       0    |       0    |       0    |       0    |
|===========================================================================|

CUDA cache and IPC cleared.
Aggressive garbage collection complete. Ready for GAT pipeline!