<a href="https://colab.research.google.com/github/iking919/Detecting_Financial_Fraud_via_GNNs/blob/main/notebooks/04_GNN_models.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# GNN Models

In [1]:
from google.colab import drive
import zipfile

drive.mount('/content/drive')

drive_path = '/content/drive/MyDrive/GNN_fraud_Project/processed_data.zip'
extract_path = '/content'

with zipfile.ZipFile(drive_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

Mounted at /content/drive

In [2]:
import os
import pandas as pd

extract_path = '/content/data/processed'
csv_files = [f for f in os.listdir(extract_path) if f.endswith('.csv')]

for file in csv_files:
    file_path = os.path.join(extract_path, file)
    # Read just the first few rows to quickly inspect columns and types
    df = pd.read_csv(file_path, nrows=5)
    print(f"\n{'='*40}\nDataset: {file}\n{'='*40}")
    print(f"Number of features: {len(df.columns)}")
    print("Features:", list(df.columns))
    display(df.head(2))

========================================
Dataset: paysim_edges.csv
========================================
Number of features: 2
Features: ['source', 'target']

   source   target
0      95  2192036
1     834  1359401

========================================
Dataset: ieee_train_edges.csv
========================================
Number of features: 2
Features: ['source', 'target']

   source  target
0   36634  164336
1  164336  223739

========================================
Dataset: elliptic_nodes.csv
========================================
Number of features: 168
Features: ['timestep', 'feature_1', 'feature_2', 'feature_3', 'feature_4', 'feature_5', 'feature_6', 'feature_7', 'feature_8', 'feature_9', 'feature_10', 'feature_11', 'feature_12', 'feature_13', 'feature_14', 'feature_15', 'feature_16', 'feature_17', 'feature_18', 'feature_19', 'feature_20', 'feature_21', 'feature_22', 'feature_23', 'feature_24', 'feature_25', 'feature_26', 'feature_27', 'feature_28', 'feature_29', 'feature_30', 'feature_31', 'feature_32', 'feature_33', 'feature_34', 'feature_35', 'feature_36', 'feature_37', 'feature_38', 'feature_39', 'feature_40', 'feature_41', 'feature_42', 'feature_43', 'feature_44', 'feature_45', 'feature_46', 'feature_47', 'feature_48', 'feature_49', 'feature_50', 'feature_51', 'feature_52', 'feature_53', 'feature_54', 'feature_55', 'feature_56', 'feature_57', 'feature_58', 'feature_59', 'feature_60', 'feature_61', 'feature_62', 'feature_63', 'feature_64', 'feature_65', 'feature_66', 'feature_67', 'feature_68', 'feature_69', 'feature_70', 'feature_71', 'feature_72', 'feature_73', 'feature_74', 'feature_75', 'feature_76', 'feature_77', 'feature_78', 'feature_79', 'feature_80', 'feature_81', 'feature_82', 'feature_83', 'feature_84', 'feature_85', 'feature_86', 'feature_87', 'feature_88', 'feature_89', 'feature_90', 'feature_91', 'feature_92', 'feature_93', 'feature_94', 'feature_95', 'feature_96', 'feature_97', 'feature_98', 'feature_99', 'feature_100', 'feature_101', 'feature_102', 'feature_103', 'feature_104', 'feature_105', 'feature_106', 'feature_107', 'feature_108', 'feature_109', 'feature_110', 'feature_111', 'feature_112', 'feature_113', 'feature_114', 'feature_115', 'feature_116', 'feature_117', 'feature_118', 'feature_119', 'feature_120', 'feature_121', 'feature_122', 'feature_123', 'feature_124', 'feature_125', 'feature_126', 'feature_127', 'feature_128', 'feature_129', 'feature_130', 'feature_131', 'feature_132', 'feature_133', 'feature_134', 'feature_135', 'feature_136', 'feature_137', 'feature_138', 'feature_139', 'feature_140', 'feature_141', 'feature_142', 'feature_143', 'feature_144', 'feature_145', 'feature_146', 'feature_147', 'feature_148', 'feature_149', 'feature_150', 'feature_151', 'feature_152', 'feature_153', 'feature_154', 'feature_155', 'feature_156', 'feature_157', 'feature_158', 'feature_159', 'feature_160', 'feature_161', 'feature_162', 'feature_163', 'feature_164', 'feature_165', 'tx_id', 'label']

,timestep,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,...,feature_158,feature_159,feature_160,feature_161,feature_162,feature_163,feature_164,feature_165,tx_id,label
0,-1.556878,0.307025,1.168821,-0.748109,7.643807,-0.053406,6.039024,21.528480,-0.146334,-0.084347,...,0.155526,0.155844,2.115930,0.016322,-0.117599,0.593442,-0.08332,-0.082052,NaN,2
1,-1.556878,0.067780,0.271911,-0.226081,2.628539,-0.053406,2.820415,1.501088,-0.146334,-0.127352,...,0.155526,0.155844,1.200416,-0.028141,-0.117599,0.270020,-0.08332,-0.082052,NaN,2

========================================
Dataset: elliptic_edges.csv
========================================
Number of features: 2
Features: ['source', 'target']

      source     target
0  230425980    5530458
1  232022460  232438397

========================================
Dataset: ieee_test_nodes.csv
========================================
Number of features: 433
Features: ['TransactionDT', 'TransactionAmt', 'ProductCD', 'card1', 'card2', 'card3', 'card4', 'card5', 'card6', 'addr1', 'addr2', 'dist1', 'dist2', 'P_emaildomain', 'R_emaildomain', 'C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7', 'C8', 'C9', 'C10', 'C11', 'C12', 'C13', 'C14', 'D1', 'D2', 'D3', 'D4', 'D5', 'D6', 'D7', 'D8', 'D9', 'D10', 'D11', 'D12', 'D13', 'D14', 'D15', 'M1', 'M2', 'M3', 'M4', 'M5', 'M6', 'M7', 'M8', 'M9', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10', 'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20', 'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'V29', 'V30', 'V31', 'V32', 'V33', 'V34', 'V35', 'V36', 'V37', 'V38', 'V39', 'V40', 'V41', 'V42', 'V43', 'V44', 'V45', 'V46', 'V47', 'V48', 'V49', 'V50', 'V51', 'V52', 'V53', 'V54', 'V55', 'V56', 'V57', 'V58', 'V59', 'V60', 'V61', 'V62', 'V63', 'V64', 'V65', 'V66', 'V67', 'V68', 'V69', 'V70', 'V71', 'V72', 'V73', 'V74', 'V75', 'V76', 'V77', 'V78', 'V79', 'V80', 'V81', 'V82', 'V83', 'V84', 'V85', 'V86', 'V87', 'V88', 'V89', 'V90', 'V91', 'V92', 'V93', 'V94', 'V95', 'V96', 'V97', 'V98', 'V99', 'V100', 'V101', 'V102', 'V103', 'V104', 'V105', 'V106', 'V107', 'V108', 'V109', 'V110', 'V111', 'V112', 'V113', 'V114', 'V115', 'V116', 'V117', 'V118', 'V119', 'V120', 'V121', 'V122', 'V123', 'V124', 'V125', 'V126', 'V127', 'V128', 'V129', 'V130', 'V131', 'V132', 'V133', 'V134', 'V135', 'V136', 'V137', 'V138', 'V139', 'V140', 'V141', 'V142', 'V143', 'V144', 'V145', 'V146', 'V147', 'V148', 'V149', 'V150', 'V151', 'V152', 'V153', 'V154', 'V155', 'V156', 'V157', 'V158', 'V159', 'V160', 'V161', 'V162', 'V163', 'V164', 'V165', 'V166', 'V167', 'V168', 'V169', 'V170', 'V171', 'V172', 'V173', 'V174', 'V175', 'V176', 'V177', 'V178', 'V179', 'V180', 'V181', 'V182', 'V183', 'V184', 'V185', 'V186', 'V187', 'V188', 'V189', 'V190', 'V191', 'V192', 'V193', 'V194', 'V195', 'V196', 'V197', 'V198', 'V199', 'V200', 'V201', 'V202', 'V203', 'V204', 'V205', 'V206', 'V207', 'V208', 'V209', 'V210', 'V211', 'V212', 'V213', 'V214', 'V215', 'V216', 'V217', 'V218', 'V219', 'V220', 'V221', 'V222', 'V223', 'V224', 'V225', 'V226', 'V227', 'V228', 'V229', 'V230', 'V231', 'V232', 'V233', 'V234', 'V235', 'V236', 'V237', 'V238', 'V239', 'V240', 'V241', 'V242', 'V243', 'V244', 'V245', 'V246', 'V247', 'V248', 'V249', 'V250', 'V251', 'V252', 'V253', 'V254', 'V255', 'V256', 'V257', 'V258', 'V259', 'V260', 'V261', 'V262', 'V263', 'V264', 'V265', 'V266', 'V267', 'V268', 'V269', 'V270', 'V271', 'V272', 'V273', 'V274', 'V275', 'V276', 'V277', 'V278', 'V279', 'V280', 'V281', 'V282', 'V283', 'V284', 'V285', 'V286', 'V287', 'V288', 'V289', 'V290', 'V291', 'V292', 'V293', 'V294', 'V295', 'V296', 'V297', 'V298', 'V299', 'V300', 'V301', 'V302', 'V303', 'V304', 'V305', 'V306', 'V307', 'V308', 'V309', 'V310', 'V311', 'V312', 'V313', 'V314', 'V315', 'V316', 'V317', 'V318', 'V319', 'V320', 'V321', 'V322', 'V323', 'V324', 'V325', 'V326', 'V327', 'V328', 'V329', 'V330', 'V331', 'V332', 'V333', 'V334', 'V335', 'V336', 'V337', 'V338', 'V339', 'id-01', 'id-02', 'id-03', 'id-04', 'id-05', 'id-06', 'id-07', 'id-08', 'id-09', 'id-10', 'id-11', 'id-12', 'id-13', 'id-14', 'id-15', 'id-16', 'id-17', 'id-18', 'id-19', 'id-20', 'id-21', 'id-22', 'id-23', 'id-24', 'id-25', 'id-26', 'id-27', 'id-28', 'id-29', 'id-30', 'id-31', 'id-32', 'id-33', 'id-34', 'id-35', 'id-36', 'id-37', 'id-38', 'DeviceType', 'DeviceInfo', 'tx_id']

,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,card6,addr1,...,id-32,id-33,id-34,id-35,id-36,id-37,id-38,DeviceType,DeviceInfo,tx_id
0,-1.792644,-0.418162,0.591741,0.092483,-1.606985,-0.283858,0.691996,0.632954,0.526399,-1.288870,...,-0.199723,0.37658,0.407556,0.565944,0.605893,0.564739,0.579979,0.569268,0.341874,0
1,-1.792635,-0.348790,0.591741,-1.163823,-1.606985,-0.283858,0.691996,0.632954,0.526399,0.065373,...,-0.199723,0.37658,0.407556,0.565944,0.605893,0.564739,0.579979,0.569268,0.341874,1

========================================
Dataset: ieee_test_edges.csv
========================================
Number of features: 2
Features: ['source', 'target']

   source  target
0  420980  449477
1  381391  393300

========================================
Dataset: paysim_nodes.csv
========================================
Number of features: 9
Features: ['log_amount', 'type_encoded', 'oldbalanceOrg', 'newbalanceOrig', 'oldbalanceDest', 'newbalanceDest', 'step', 'tx_id', 'label']

,log_amount,type_encoded,oldbalanceOrg,newbalanceOrig,oldbalanceDest,newbalanceDest,step,tx_id,label
0,-0.907462,0.952399,-0.229810,-0.237622,-0.323814,-0.333411,-1.703042,0,0
1,-1.824023,0.952399,-0.281359,-0.285812,-0.323814,-0.333411,-1.703042,1,0

========================================
Dataset: ieee_train_nodes.csv
========================================
Number of features: 434
Features: ['TransactionDT', 'TransactionAmt', 'ProductCD', 'card1', 'card2', 'card3', 'card4', 'card5', 'card6', 'addr1', 'addr2', 'dist1', 'dist2', 'P_emaildomain', 'R_emaildomain', 'C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7', 'C8', 'C9', 'C10', 'C11', 'C12', 'C13', 'C14', 'D1', 'D2', 'D3', 'D4', 'D5', 'D6', 'D7', 'D8', 'D9', 'D10', 'D11', 'D12', 'D13', 'D14', 'D15', 'M1', 'M2', 'M3', 'M4', 'M5', 'M6', 'M7', 'M8', 'M9', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10', 'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20', 'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'V29', 'V30', 'V31', 'V32', 'V33', 'V34', 'V35', 'V36', 'V37', 'V38', 'V39', 'V40', 'V41', 'V42', 'V43', 'V44', 'V45', 'V46', 'V47', 'V48', 'V49', 'V50', 'V51', 'V52', 'V53', 'V54', 'V55', 'V56', 'V57', 'V58', 'V59', 'V60', 'V61', 'V62', 'V63', 'V64', 'V65', 'V66', 'V67', 'V68', 'V69', 'V70', 'V71', 'V72', 'V73', 'V74', 'V75', 'V76', 'V77', 'V78', 'V79', 'V80', 'V81', 'V82', 'V83', 'V84', 'V85', 'V86', 'V87', 'V88', 'V89', 'V90', 'V91', 'V92', 'V93', 'V94', 'V95', 'V96', 'V97', 'V98', 'V99', 'V100', 'V101', 'V102', 'V103', 'V104', 'V105', 'V106', 'V107', 'V108', 'V109', 'V110', 'V111', 'V112', 'V113', 'V114', 'V115', 'V116', 'V117', 'V118', 'V119', 'V120', 'V121', 'V122', 'V123', 'V124', 'V125', 'V126', 'V127', 'V128', 'V129', 'V130', 'V131', 'V132', 'V133', 'V134', 'V135', 'V136', 'V137', 'V138', 'V139', 'V140', 'V141', 'V142', 'V143', 'V144', 'V145', 'V146', 'V147', 'V148', 'V149', 'V150', 'V151', 'V152', 'V153', 'V154', 'V155', 'V156', 'V157', 'V158', 'V159', 'V160', 'V161', 'V162', 'V163', 'V164', 'V165', 'V166', 'V167', 'V168', 'V169', 'V170', 'V171', 'V172', 'V173', 'V174', 'V175', 'V176', 'V177', 'V178', 'V179', 'V180', 'V181', 'V182', 'V183', 'V184', 'V185', 'V186', 'V187', 'V188', 'V189', 'V190', 'V191', 'V192', 'V193', 'V194', 'V195', 'V196', 'V197', 'V198', 'V199', 'V200', 'V201', 'V202', 'V203', 'V204', 'V205', 'V206', 'V207', 'V208', 'V209', 'V210', 'V211', 'V212', 'V213', 'V214', 'V215', 'V216', 'V217', 'V218', 'V219', 'V220', 'V221', 'V222', 'V223', 'V224', 'V225', 'V226', 'V227', 'V228', 'V229', 'V230', 'V231', 'V232', 'V233', 'V234', 'V235', 'V236', 'V237', 'V238', 'V239', 'V240', 'V241', 'V242', 'V243', 'V244', 'V245', 'V246', 'V247', 'V248', 'V249', 'V250', 'V251', 'V252', 'V253', 'V254', 'V255', 'V256', 'V257', 'V258', 'V259', 'V260', 'V261', 'V262', 'V263', 'V264', 'V265', 'V266', 'V267', 'V268', 'V269', 'V270', 'V271', 'V272', 'V273', 'V274', 'V275', 'V276', 'V277', 'V278', 'V279', 'V280', 'V281', 'V282', 'V283', 'V284', 'V285', 'V286', 'V287', 'V288', 'V289', 'V290', 'V291', 'V292', 'V293', 'V294', 'V295', 'V296', 'V297', 'V298', 'V299', 'V300', 'V301', 'V302', 'V303', 'V304', 'V305', 'V306', 'V307', 'V308', 'V309', 'V310', 'V311', 'V312', 'V313', 'V314', 'V315', 'V316', 'V317', 'V318', 'V319', 'V320', 'V321', 'V322', 'V323', 'V324', 'V325', 'V326', 'V327', 'V328', 'V329', 'V330', 'V331', 'V332', 'V333', 'V334', 'V335', 'V336', 'V337', 'V338', 'V339', 'id_01', 'id_02', 'id_03', 'id_04', 'id_05', 'id_06', 'id_07', 'id_08', 'id_09', 'id_10', 'id_11', 'id_12', 'id_13', 'id_14', 'id_15', 'id_16', 'id_17', 'id_18', 'id_19', 'id_20', 'id_21', 'id_22', 'id_23', 'id_24', 'id_25', 'id_26', 'id_27', 'id_28', 'id_29', 'id_30', 'id_31', 'id_32', 'id_33', 'id_34', 'id_35', 'id_36', 'id_37', 'id_38', 'DeviceType', 'DeviceInfo', 'tx_id', 'label']

,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,card6,addr1,...,id_33,id_34,id_35,id_36,id_37,id_38,DeviceType,DeviceInfo,tx_id,label
0,-1.577987,-0.278167,0.54725,0.821695,-0.009783,-0.281425,-2.187837,-1.396380,-1.675109,0.243321,...,0.349681,0.36423,0.521097,0.555553,0.522078,0.524266,0.528289,0.319736,0,0
1,-1.577986,-0.443327,0.54725,-1.457558,0.264810,-0.281425,-1.222461,-2.368254,-1.675109,0.347543,...,0.349681,0.36423,0.521097,0.555553,0.522078,0.524266,0.528289,0.319736,1,0

## GraphSAGE (Graph Sample and Aggregate) Model

In [3]:
!pip install torch_geometric

Collecting torch_geometric
  Downloading torch_geometric-2.7.0-py3-none-any.whl.metadata (63 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.7/63.7 kB 5.1 MB/s eta 0:00:00
Requirement already satisfied: aiohttp in /usr/local/lib/python3.12/dist-packages (from torch_geometric) (3.13.5)
Requirement already satisfied: fsspec in /usr/local/lib/python3.12/dist-packages (from torch_geometric) (2025.3.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch_geometric) (3.1.6)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from torch_geometric) (2.0.2)
Requirement already satisfied: psutil>=5.8.0 in /usr/local/lib/python3.12/dist-packages (from torch_geometric) (5.9.5)
Requirement already satisfied: pyparsing in /usr/local/lib/python3.12/dist-packages (from torch_geometric) (3.3.2)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from torch_geometric) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from torch_geometric) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from torch_geometric) (3.6.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch_geometric) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch_geometric) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch_geometric) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch_geometric) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch_geometric) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch_geometric) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch_geometric) (1.23.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch_geometric) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->torch_geometric) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->torch_geometric) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->torch_geometric) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->torch_geometric) (2026.2.25)
Requirement already satisfied: typing-extensions>=4.2 in /usr/local/lib/python3.12/dist-packages (from aiosignal>=1.4.0->aiohttp->torch_geometric) (4.15.0)
Downloading torch_geometric-2.7.0-py3-none-any.whl (1.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 48.4 MB/s eta 0:00:00
Installing collected packages: torch_geometric
Successfully installed torch_geometric-2.7.0

In [4]:
import pandas as pd
import numpy as np
import torch
import torch.nn.functional as F
from torch_geometric.data import Data
from torch_geometric.nn import SAGEConv
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.metrics import roc_auc_score, f1_score, confusion_matrix, classification_report
from sklearn.model_selection import train_test_split

class FraudGraphSAGE(torch.nn.Module):
    def __init__(self, in_channels, hidden_channels, out_channels):
        super(FraudGraphSAGE, self).__init__()
        self.conv1 = SAGEConv(in_channels, hidden_channels)
        self.conv2 = SAGEConv(hidden_channels, out_channels)

    def forward(self, x, edge_index):
        x = self.conv1(x, edge_index)
        x = F.relu(x)
        x = F.dropout(x, p=0.3, training=self.training)
        x = self.conv2(x, edge_index)
        return x

def load_graph_data(nodes_filepath, edges_filepath, target_col):
    print(f"Loading graph data...")
    nodes_df = pd.read_csv(nodes_filepath)
    edges_df = pd.read_csv(edges_filepath)

    label_mapping = {'1': 1, 1: 1, '2': 0, 2: 0, 'unknown': -1, '3': -1, 3: -1, '0': 0, 0: 0}
    nodes_df[target_col] = nodes_df[target_col].map(label_mapping)

    node_id_col = 'tx_id' if 'tx_id' in nodes_df.columns else ('TransactionID' if 'TransactionID' in nodes_df.columns else None)

    if node_id_col:
        if nodes_df[node_id_col].duplicated().any():
            print(f"Warning: Duplicate node IDs found in '{node_id_col}'. Keeping first.")
            nodes_df = nodes_df.drop_duplicates(subset=[node_id_col], keep='first')

        original_node_ids = nodes_df[node_id_col].values
        node_id_to_idx = {id: i for i, id in enumerate(original_node_ids)}
        edges_df['source'] = edges_df['source'].map(node_id_to_idx)
        edges_df['target'] = edges_df['target'].map(node_id_to_idx)
        edges_df.dropna(subset=['source', 'target'], inplace=True)

        features_to_drop = [target_col, node_id_col]
        X = nodes_df.drop(columns=features_to_drop, errors='ignore').select_dtypes(include=[np.number]).values
    else:
        X = nodes_df.drop(columns=[target_col], errors='ignore').select_dtypes(include=[np.number]).values

    y = nodes_df[target_col].values
    imputer = SimpleImputer(strategy='mean')
    X_imputed = imputer.fit_transform(X)
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X_imputed)

    x_tensor = torch.tensor(X_scaled, dtype=torch.float)
    y_tensor = torch.tensor(y, dtype=torch.float)

    source_nodes = edges_df['source'].astype(int).values
    target_nodes = edges_df['target'].astype(int).values
    edge_index = torch.tensor(np.vstack((source_nodes, target_nodes)), dtype=torch.long)

    data = Data(x=x_tensor, edge_index=edge_index, y=y_tensor)

    known_indices = np.where((y == 0) | (y == 1))[0]

    if len(np.unique(y[known_indices])) < 2:
        print("Warning: Only one class found in labels. Training may fail.")
        train_indices, test_indices = train_test_split(known_indices, test_size=0.2, random_state=42)
    else:
        train_indices, test_indices = train_test_split(known_indices, test_size=0.2, stratify=y[known_indices], random_state=42)

    train_mask = torch.zeros(data.num_nodes, dtype=torch.bool)
    test_mask = torch.zeros(data.num_nodes, dtype=torch.bool)
    train_mask[train_indices] = True
    test_mask[test_indices] = True
    data.train_mask = train_mask
    data.test_mask = test_mask

    num_pos = int((y_tensor[train_mask] == 1).sum().item())
    num_neg = int((y_tensor[train_mask] == 0).sum().item())
    pos_weight = torch.tensor([num_neg / max(1, num_pos)], dtype=torch.float)

    return data, pos_weight

def train_gnn(model, data, pos_weight, device, epochs=200, lr=0.01):
    model.to(device)
    data = data.to(device)
    pos_weight = pos_weight.to(device)
    criterion = torch.nn.BCEWithLogitsLoss(pos_weight=pos_weight)
    optimizer = torch.optim.Adam(model.parameters(), lr=lr, weight_decay=5e-4)

    print("Starting GNN training...")
    for epoch in range(epochs):
        model.train()
        optimizer.zero_grad()
        out = model(data.x, data.edge_index).squeeze()
        loss = criterion(out[data.train_mask], data.y[data.train_mask])
        loss.backward()
        optimizer.step()
        if (epoch + 1) % 20 == 0:
            print(f'Epoch {epoch+1:03d}/{epochs} | Loss: {loss:.4f}')

def evaluate_gnn(model, data, device):
    model.eval()
    data = data.to(device)
    with torch.no_grad():
        out = model(data.x, data.edge_index).squeeze()
        probs = torch.sigmoid(out)
        preds = (probs > 0.5).float()
        test_probs = probs[data.test_mask].cpu().numpy()
        test_preds = preds[data.test_mask].cpu().numpy()
        test_y = data.y[data.test_mask].cpu().numpy()

    print("\n--- GNN Results ---")
    if len(np.unique(test_y)) > 1:
        auc_roc = roc_auc_score(test_y, test_probs)
        print(f"AUC-ROC: {auc_roc:.4f}")
    else:
        print("AUC-ROC: Not defined (only one class in test set)")

    print(f"F1-Score: {f1_score(test_y, test_preds, zero_division=0):.4f}")
    print("Confusion Matrix:")
    print(confusion_matrix(test_y, test_preds))
    print("\nClassification Report:")
    print(classification_report(test_y, test_preds, zero_division=0))

def run_graphsage_pipeline(dataset_name, nodes_filepath, edges_filepath, target_col):
    print("="*50 + f"\n--- Running GraphSAGE Pipeline for {dataset_name} ---\n" + "="*50)
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    data, loss_weight = load_graph_data(nodes_filepath, edges_filepath, target_col)
    model = FraudGraphSAGE(data.num_features, 64, 1)
    train_gnn(model, data, loss_weight, device, epochs=200)
    evaluate_gnn(model, data, device)
    return model

paysim_model = run_graphsage_pipeline("PaySim", "/content/data/processed/paysim_nodes.csv", "/content/data/processed/paysim_edges.csv", "label")
ieee_model = run_graphsage_pipeline("IEEE-CIS", "/content/data/processed/ieee_train_nodes.csv", "/content/data/processed/ieee_train_edges.csv", "label")
elliptic_model = run_graphsage_pipeline("Elliptic", "/content/data/processed/elliptic_nodes.csv", "/content/data/processed/elliptic_edges.csv", "label")

==================================================
--- Running GraphSAGE Pipeline for PaySim ---
==================================================
Loading graph data...
Starting GNN training...
Epoch 020/200 | Loss: 0.8377
Epoch 040/200 | Loss: 0.6981
Epoch 060/200 | Loss: 0.6081
Epoch 080/200 | Loss: 0.5438
Epoch 100/200 | Loss: 0.4871
Epoch 120/200 | Loss: 0.4389
Epoch 140/200 | Loss: 0.3983
Epoch 160/200 | Loss: 0.3674
Epoch 180/200 | Loss: 0.3376
Epoch 200/200 | Loss: 0.3180

--- GNN Results ---
AUC-ROC: 0.9922
F1-Score: 0.0558
Confusion Matrix:
[[1218994   51887]
 [    106    1537]]

Classification Report:
              precision    recall  f1-score   support

         0.0       1.00      0.96      0.98   1270881
         1.0       0.03      0.94      0.06      1643

    accuracy                           0.96   1272524
   macro avg       0.51      0.95      0.52   1272524
weighted avg       1.00      0.96      0.98   1272524

==================================================
--- Running GraphSAGE Pipeline for IEEE-CIS ---
==================================================
Loading graph data...
Starting GNN training...
Epoch 020/200 | Loss: 0.9537
Epoch 040/200 | Loss: 0.8748
Epoch 060/200 | Loss: 0.8288
Epoch 080/200 | Loss: 0.7936
Epoch 100/200 | Loss: 0.7651
Epoch 120/200 | Loss: 0.7387
Epoch 140/200 | Loss: 0.7287
Epoch 160/200 | Loss: 0.7041
Epoch 180/200 | Loss: 0.6990
Epoch 200/200 | Loss: 0.6843

--- GNN Results ---
AUC-ROC: 0.8989
F1-Score: 0.2912
Confusion Matrix:
[[99662 14313]
 [  990  3143]]

Classification Report:
              precision    recall  f1-score   support

         0.0       0.99      0.87      0.93    113975
         1.0       0.18      0.76      0.29      4133

    accuracy                           0.87    118108
   macro avg       0.59      0.82      0.61    118108
weighted avg       0.96      0.87      0.91    118108

==================================================
--- Running GraphSAGE Pipeline for Elliptic ---
==================================================
Loading graph data...
Warning: Duplicate node IDs found in 'tx_id'. Keeping first.
Starting GNN training...
Epoch 020/200 | Loss: 0.3851
Epoch 040/200 | Loss: 0.2189
Epoch 060/200 | Loss: 0.1572
Epoch 080/200 | Loss: 0.1127
Epoch 100/200 | Loss: 0.0935
Epoch 120/200 | Loss: 0.0843
Epoch 140/200 | Loss: 0.0773
Epoch 160/200 | Loss: 0.0722
Epoch 180/200 | Loss: 0.0703
Epoch 200/200 | Loss: 0.0703

--- GNN Results ---
AUC-ROC: 0.9737
F1-Score: 0.8168
Confusion Matrix:
[[1913   40]
 [  34  165]]

Classification Report:
              precision    recall  f1-score   support

         0.0       0.98      0.98      0.98      1953
         1.0       0.80      0.83      0.82       199

    accuracy                           0.97      2152
   macro avg       0.89      0.90      0.90      2152
weighted avg       0.97      0.97      0.97      2152

## GCN (Graph Convolutional Network) Model

In [6]:
import torch
import torch.nn.functional as F
from torch_geometric.nn import GCNConv

# 1. New GCN Model Architecture
class FraudGCN(torch.nn.Module):
    def __init__(self, in_channels, hidden_channels, out_channels):
        super(FraudGCN, self).__init__()
        # Swapping SAGEConv for standard GCNConv
        self.conv1 = GCNConv(in_channels, hidden_channels)
        self.conv2 = GCNConv(hidden_channels, out_channels)

    def forward(self, x, edge_index):
        # First GCN layer
        x = self.conv1(x, edge_index)
        x = F.relu(x)
        x = F.dropout(x, p=0.3, training=self.training)

        # Second GCN layer
        x = self.conv2(x, edge_index)
        return x

# 2. GCN Pipeline Execution
def run_gcn_pipeline(dataset_name, nodes_filepath, edges_filepath, target_col):
    print("="*50 + f"\n--- Running GCN Pipeline for {dataset_name} ---\n" + "="*50)
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

    # Utilizing your fixed data loader function
    data, loss_weight = load_graph_data(nodes_filepath, edges_filepath, target_col)

    # Initialize the new GCN model
    model = FraudGCN(data.num_features, 64, 1)

    # Train and evaluate using your existing functions
    # Dropping epochs to 100 to match your latest run
    train_gnn(model, data, loss_weight, device, epochs=200)
    evaluate_gnn(model, data, device)

    return model

# ==========================================
# Execution Block
# ==========================================
paysim_gcn = run_gcn_pipeline(
    "PaySim",
    "/content/data/processed/paysim_nodes.csv",
    "/content/data/processed/paysim_edges.csv",
    "label"
)

ieee_gcn = run_gcn_pipeline(
    "IEEE-CIS",
    "/content/data/processed/ieee_train_nodes.csv",
    "/content/data/processed/ieee_train_edges.csv",
    "label"
)

elliptic_gcn = run_gcn_pipeline(
    "Elliptic",
    "/content/data/processed/elliptic_nodes.csv",
    "/content/data/processed/elliptic_edges.csv",
    "label"
)

==================================================
--- Running GCN Pipeline for PaySim ---
==================================================
Loading graph data...
Starting GNN training...
Epoch 020/200 | Loss: 0.9711
Epoch 040/200 | Loss: 0.9416
Epoch 060/200 | Loss: 0.9184
Epoch 080/200 | Loss: 0.8906
Epoch 100/200 | Loss: 0.8567
Epoch 120/200 | Loss: 0.8178
Epoch 140/200 | Loss: 0.7810
Epoch 160/200 | Loss: 0.7565
Epoch 180/200 | Loss: 0.7420
Epoch 200/200 | Loss: 0.7292

--- GNN Results ---
AUC-ROC: 0.9170
F1-Score: 0.0278
Confusion Matrix:
[[1190511   80370]
 [    489    1154]]

Classification Report:
              precision    recall  f1-score   support

         0.0       1.00      0.94      0.97   1270881
         1.0       0.01      0.70      0.03      1643

    accuracy                           0.94   1272524
   macro avg       0.51      0.82      0.50   1272524
weighted avg       1.00      0.94      0.97   1272524

==================================================
--- Running GCN Pipeline for IEEE-CIS ---
==================================================
Loading graph data...
Starting GNN training...
Epoch 020/200 | Loss: 1.1848
Epoch 040/200 | Loss: 1.1435
Epoch 060/200 | Loss: 1.1257
Epoch 080/200 | Loss: 1.1177
Epoch 100/200 | Loss: 1.1080
Epoch 120/200 | Loss: 1.1002
Epoch 140/200 | Loss: 1.0918
Epoch 160/200 | Loss: 1.0844
Epoch 180/200 | Loss: 1.0762
Epoch 200/200 | Loss: 1.0710

--- GNN Results ---
AUC-ROC: 0.7666
F1-Score: 0.1703
Confusion Matrix:
[[91648 22327]
 [ 1671  2462]]

Classification Report:
              precision    recall  f1-score   support

         0.0       0.98      0.80      0.88    113975
         1.0       0.10      0.60      0.17      4133

    accuracy                           0.80    118108
   macro avg       0.54      0.70      0.53    118108
weighted avg       0.95      0.80      0.86    118108

==================================================
--- Running GCN Pipeline for Elliptic ---
==================================================
Loading graph data...
Warning: Duplicate node IDs found in 'tx_id'. Keeping first.
Starting GNN training...
Epoch 020/200 | Loss: 0.8393
Epoch 040/200 | Loss: 0.7437
Epoch 060/200 | Loss: 0.6753
Epoch 080/200 | Loss: 0.6226
Epoch 100/200 | Loss: 0.6028
Epoch 120/200 | Loss: 0.5572
Epoch 140/200 | Loss: 0.5514
Epoch 160/200 | Loss: 0.5183
Epoch 180/200 | Loss: 0.5052
Epoch 200/200 | Loss: 0.5003

--- GNN Results ---
AUC-ROC: 0.8107
F1-Score: 0.4508
Confusion Matrix:
[[1695  258]
 [  66  133]]

Classification Report:
              precision    recall  f1-score   support

         0.0       0.96      0.87      0.91      1953
         1.0       0.34      0.67      0.45       199

    accuracy                           0.85      2152
   macro avg       0.65      0.77      0.68      2152
weighted avg       0.90      0.85      0.87      2152

## GAT (Graph Attention Networks) Model

In [8]:
import torch
import torch.nn.functional as F
from torch_geometric.nn import GATConv

# 1. New GAT Model Architecture
class FraudGAT(torch.nn.Module):
    def __init__(self, in_channels, hidden_channels, out_channels, heads=4):
        super(FraudGAT, self).__init__()
        # GAT uses multiple "attention heads" to learn different relationship types
        # We divide hidden_channels by heads so the output size matches our other models
        self.conv1 = GATConv(in_channels, hidden_channels // heads, heads=heads)
        self.conv2 = GATConv(hidden_channels, out_channels, heads=1, concat=False)

    def forward(self, x, edge_index):
        # First GAT layer
        x = self.conv1(x, edge_index)
        x = F.elu(x) # ELU is standard practice for GATs instead of ReLU
        x = F.dropout(x, p=0.3, training=self.training)

        # Second GAT layer
        x = self.conv2(x, edge_index)
        return x

# 2. GAT Pipeline Execution
def run_gat_pipeline(dataset_name, nodes_filepath, edges_filepath, target_col):
    print("="*50 + f"\n--- Running GAT Pipeline for {dataset_name} ---\n" + "="*50)
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

    data, loss_weight = load_graph_data(nodes_filepath, edges_filepath, target_col)

    # Initialize the GAT model
    model = FraudGAT(data.num_features, 64, 1)

    # Train and evaluate
    train_gnn(model, data, loss_weight, device, epochs=200)
    evaluate_gnn(model, data, device)

    return model

# ==========================================
# Execution Block
# ==========================================
paysim_gat = run_gat_pipeline(
    "PaySim",
    "/content/data/processed/paysim_nodes.csv",
    "/content/data/processed/paysim_edges.csv",
    "label"
)

ieee_gat = run_gat_pipeline(
    "IEEE-CIS",
    "/content/data/processed/ieee_train_nodes.csv",
    "/content/data/processed/ieee_train_edges.csv",
    "label"
)

elliptic_gat = run_gat_pipeline(
    "Elliptic",
    "/content/data/processed/elliptic_nodes.csv",
    "/content/data/processed/elliptic_edges.csv",
    "label"
)

==================================================
--- Running GAT Pipeline for PaySim ---
==================================================
Loading graph data...
Starting GNN training...
Epoch 020/200 | Loss: 0.9865
Epoch 040/200 | Loss: 0.8834
Epoch 060/200 | Loss: 0.8106
Epoch 080/200 | Loss: 0.7585
Epoch 100/200 | Loss: 0.7209
Epoch 120/200 | Loss: 0.6913
Epoch 140/200 | Loss: 0.6758
Epoch 160/200 | Loss: 0.6629
Epoch 180/200 | Loss: 0.6462
Epoch 200/200 | Loss: 0.6407

--- GNN Results ---
AUC-ROC: 0.9406
F1-Score: 0.0432
Confusion Matrix:
[[1213815   57066]
 [    347    1296]]

Classification Report:
              precision    recall  f1-score   support

         0.0       1.00      0.96      0.98   1270881
         1.0       0.02      0.79      0.04      1643

    accuracy                           0.95   1272524
   macro avg       0.51      0.87      0.51   1272524
weighted avg       1.00      0.95      0.98   1272524

==================================================
--- Running GAT Pipeline for IEEE-CIS ---
==================================================
Loading graph data...
Starting GNN training...
Epoch 020/200 | Loss: 1.2135
Epoch 040/200 | Loss: 1.1318
Epoch 060/200 | Loss: 1.0947
Epoch 080/200 | Loss: 1.0677
Epoch 100/200 | Loss: 1.0480
Epoch 120/200 | Loss: 1.0306
Epoch 140/200 | Loss: 1.0078
Epoch 160/200 | Loss: 0.9879
Epoch 180/200 | Loss: 0.9758
Epoch 200/200 | Loss: 0.9557

--- GNN Results ---
AUC-ROC: 0.8119
F1-Score: 0.2178
Confusion Matrix:
[[96120 17855]
 [ 1446  2687]]

Classification Report:
              precision    recall  f1-score   support

         0.0       0.99      0.84      0.91    113975
         1.0       0.13      0.65      0.22      4133

    accuracy                           0.84    118108
   macro avg       0.56      0.75      0.56    118108
weighted avg       0.96      0.84      0.88    118108

==================================================
--- Running GAT Pipeline for Elliptic ---
==================================================
Loading graph data...
Warning: Duplicate node IDs found in 'tx_id'. Keeping first.
Starting GNN training...
Epoch 020/200 | Loss: 0.7600
Epoch 040/200 | Loss: 0.6084
Epoch 060/200 | Loss: 0.5196
Epoch 080/200 | Loss: 0.4599
Epoch 100/200 | Loss: 0.4104
Epoch 120/200 | Loss: 0.3597
Epoch 140/200 | Loss: 0.3432
Epoch 160/200 | Loss: 0.3247
Epoch 180/200 | Loss: 0.3301
Epoch 200/200 | Loss: 0.3135

--- GNN Results ---
AUC-ROC: 0.9052
F1-Score: 0.5811
Confusion Matrix:
[[1776  177]
 [  45  154]]

Classification Report:
              precision    recall  f1-score   support

         0.0       0.98      0.91      0.94      1953
         1.0       0.47      0.77      0.58       199

    accuracy                           0.90      2152
   macro avg       0.72      0.84      0.76      2152
weighted avg       0.93      0.90      0.91      2152